"""Generated from the controlled SQL CHECK round trip; do not hand edit."""

CHECK_DDL_SHA256: str = "sha256:4ba5f294030e7c2da8cb867adfbb2fcba45ba87df623fa24f9f7d86e858ae990"
CHECK_DATABASE_COLLATION: str = "SQL_Latin1_General_CP1_CI_AS"
CHECK_DEFINITIONS: dict[str, str] = {
    "ck_c_authority_singleton": "([singleton]=(1))",
    "ck_c_authority_version": "([schema_version]=(2))",
    "ck_c_domain_connector": "([connector]='mssql' AND datalength([connector])=(5) OR [connector]='clickhouse' AND datalength([connector])=(10) OR [connector]='postgres' AND datalength([connector])=(8))",
    "ck_c_domain_epoch": "([fencing_epoch]>=(0) AND ([owner_key] IS NULL OR [fencing_epoch]>(0)))",
    "ck_c_domains_guard_id": "(datalength([guard_id])=(71))",
    "ck_c_domains_owner_key": "(datalength([owner_key])=(71))",
    "ck_c_domains_physical_subject_sha256": "(datalength([physical_subject_sha256])=(71))",
    "ck_c_issued_authorities_operation_key": "(datalength([operation_key])=(71))",
    "ck_c_issued_connector": "([connector]='mssql' AND datalength([connector])=(5) OR [connector]='clickhouse' AND datalength([connector])=(10))",
    "ck_c_operation_document": "([operation_family]='execution' AND datalength([operation_family])=(9) AND (datalength([operation_document])>=(1) AND datalength([operation_document])<=(8388608)) OR [operation_family]='qualification' AND datalength([operation_family])=(13) AND (datalength([operation_document])>=(1) AND datalength([operation_document])<=(1048576)))",
    "ck_c_operation_domain_epoch": "([fencing_epoch]>(0))",
    "ck_c_operation_domains_guard_id": "(datalength([guard_id])=(71))",
    "ck_c_operation_domains_operation_key": "(datalength([operation_key])=(71))",
    "ck_c_operation_domains_owner_key": "(datalength([owner_key])=(71))",
    "ck_c_operation_replay": "([operation_family]<>'execution' OR [operation_key]=[replay_key])",
    "ck_c_operation_state": "([state]='RUNNING' AND datalength([state])=(7) OR [state]='SUCCEEDED' AND datalength([state])=(9) OR [state]='FAILED' AND datalength([state])=(6) OR [state]='COMMIT_UNKNOWN' AND datalength([state])=(14))",
    "ck_c_operation_terminal": "([state]='RUNNING' OR [state]='COMMIT_UNKNOWN' OR [closed_gates_sha256] IS NOT NULL AND [quiescence_sha256] IS NOT NULL AND [outcome_evidence_sha256] IS NOT NULL)",
    "ck_c_operations_closed_gates_sha256": "(datalength([closed_gates_sha256])=(71))",
    "ck_c_operations_operation_key": "(datalength([operation_key])=(71))",
    "ck_c_operations_outcome_evidence_sha256": "(datalength([outcome_evidence_sha256])=(71))",
    "ck_c_operations_owner_key": "(datalength([owner_key])=(71))",
    "ck_c_operations_owner_subject_sha256": "(datalength([owner_subject_sha256])=(71))",
    "ck_c_operations_quiescence_sha256": "(datalength([quiescence_sha256])=(71))",
    "ck_c_operations_replay_key": "(datalength([replay_key])=(71))",
    "ck_c_owner_document": "([owner_kind]='execution' AND datalength([owner_kind])=(9) AND (datalength([subject_document])>=(1) AND datalength([subject_document])<=(8388608)) OR [owner_kind]='qualification' AND datalength([owner_kind])=(13) AND (datalength([subject_document])>=(1) AND datalength([subject_document])<=(1048576)))",
    "ck_c_owner_domain_document": "(datalength([claim_document])>=(1) AND datalength([claim_document])<=(8388608))",
    "ck_c_owner_domain_epoch": "([fencing_epoch]>(0))",
    "ck_c_owner_domains_guard_id": "(datalength([guard_id])=(71))",
    "ck_c_owner_domains_owner_key": "(datalength([owner_key])=(71))",
    "ck_c_owner_state": "([owner_kind]='execution' AND datalength([owner_kind])=(9) AND ([state]='PREPARED' AND datalength([state])=(8) OR [state]='ACTIVE' AND datalength([state])=(6) OR [state]='RETIRING' AND datalength([state])=(8) OR [state]='RETIRED' AND datalength([state])=(7)) OR [owner_kind]='qualification' AND datalength([owner_kind])=(13) AND ([state]='PREPARED' AND datalength([state])=(8) OR [state]='ACTIVE' AND datalength([state])=(6) OR [state]='SEALING' AND datalength([state])=(7) OR [state]='SEALED' AND datalength([state])=(6) OR [state]='TRANSFERRED' AND datalength([state])=(11) OR [state]='RETIRED' AND datalength([state])=(7)))",
    "ck_c_owners_owner_key": "(datalength([owner_key])=(71))",
    "ck_c_owners_subject_sha256": "(datalength([subject_sha256])=(71))",
    "ck_c_proof_document": "(datalength([proof_document])>=(1) AND datalength([proof_document])<=(8388608))",
    "ck_c_proof_family": "([operation_family]='execution' AND datalength([operation_family])=(9))",
    "ck_c_proof_kind": "([kind]='CLOSED_GATES' AND datalength([kind])=(12) OR [kind]='QUIESCENCE' AND datalength([kind])=(10) OR [kind]='OUTCOME' AND datalength([kind])=(7))",
    "ck_c_proofs_operation_key": "(datalength([operation_key])=(71))",
    "ck_c_proofs_proof_sha256": "(datalength([proof_sha256])=(71))",
}
CHECK_METADATA: dict[str, tuple[int, int]] = {
    "ck_c_authority_singleton": (1, 1),
    "ck_c_authority_version": (2, 1),
    "ck_c_domain_connector": (2, 1),
    "ck_c_domain_epoch": (0, 1),
    "ck_c_domains_guard_id": (1, 1),
    "ck_c_domains_owner_key": (6, 1),
    "ck_c_domains_physical_subject_sha256": (4, 1),
    "ck_c_issued_authorities_operation_key": (1, 1),
    "ck_c_issued_connector": (2, 1),
    "ck_c_operation_document": (0, 1),
    "ck_c_operation_domain_epoch": (4, 1),
    "ck_c_operation_domains_guard_id": (3, 1),
    "ck_c_operation_domains_operation_key": (1, 1),
    "ck_c_operation_domains_owner_key": (2, 1),
    "ck_c_operation_replay": (0, 1),
    "ck_c_operation_state": (7, 1),
    "ck_c_operation_terminal": (0, 1),
    "ck_c_operations_closed_gates_sha256": (8, 1),
    "ck_c_operations_operation_key": (1, 1),
    "ck_c_operations_outcome_evidence_sha256": (10, 1),
    "ck_c_operations_owner_key": (3, 1),
    "ck_c_operations_owner_subject_sha256": (4, 1),
    "ck_c_operations_quiescence_sha256": (9, 1),
    "ck_c_operations_replay_key": (5, 1),
    "ck_c_owner_document": (0, 1),
    "ck_c_owner_domain_document": (3, 1),
    "ck_c_owner_domain_epoch": (4, 1),
    "ck_c_owner_domains_guard_id": (2, 1),
    "ck_c_owner_domains_owner_key": (1, 1),
    "ck_c_owner_state": (0, 1),
    "ck_c_owners_owner_key": (1, 1),
    "ck_c_owners_subject_sha256": (4, 1),
    "ck_c_proof_document": (5, 1),
    "ck_c_proof_family": (2, 1),
    "ck_c_proof_kind": (3, 1),
    "ck_c_proofs_operation_key": (1, 1),
    "ck_c_proofs_proof_sha256": (4, 1),
}
