"""Immutable Python source admission; run before launch or inside guarded child."""

import hashlib
import os
import stat
from pathlib import Path

from dpone.contracts.mssql_tds_api import canonical_json_bytes


def worker_installation_digest(package_root: Path) -> str:
    """Fingerprint the installed framework sources, excluding generated bytecode.

    SDK version/binary and interpreter admission remain separate preflight checks.
    This digest binds this source installation only and is not a signed receipt.
    """
    root = package_root / "dpone"
    if not (root / "app/mssql_tds_worker_bootstrap.py").is_file():
        raise ValueError("mssql_native.tds_installation_invalid")
    digest = hashlib.sha256()
    total = 0
    paths: list[Path] = []
    for count, path in enumerate(root.rglob("*")):
        if count >= 30000 or path.is_symlink():
            raise ValueError("mssql_native.tds_installation_invalid")
        if path.suffix in {".so", ".pyd"} or (path.suffix == ".pyc" and path.parent.name != "__pycache__"):
            raise ValueError("mssql_native.tds_installation_invalid")
        if path.suffix == ".py":
            if len(paths) >= 10000:
                raise ValueError("mssql_native.tds_installation_invalid")
            paths.append(path)
    for path in sorted(paths):
        if not stat.S_ISREG(path.lstat().st_mode):
            raise ValueError("mssql_native.tds_installation_invalid")
        fd = os.open(path, os.O_RDONLY | os.O_NONBLOCK | os.O_NOFOLLOW)
        with os.fdopen(fd, "rb") as stream:
            if not stat.S_ISREG(os.fstat(stream.fileno()).st_mode):
                raise ValueError("mssql_native.tds_installation_invalid")
            data = stream.read(4 * 1024**2 + 1)
        if len(data) > 4 * 1024**2:
            raise ValueError("mssql_native.tds_installation_invalid")
        total += len(data)
        if total > 128 * 1024**2:
            raise ValueError("mssql_native.tds_installation_invalid")
        digest.update(canonical_json_bytes([str(path.relative_to(root)), hashlib.sha256(data).hexdigest()]))
    return digest.hexdigest()
