"""The fixed 128-column PostgreSQL source recipe, independent of test runners.

DDL suffixes and seed expressions retain their original placeholder bytes.
They are trusted source definitions, not parsed caller SQL or backend values.
"""

from dataclasses import dataclass

WIDE_COLUMN_TARGET = 128


@dataclass(frozen=True, slots=True)
class PostgresFixtureColumn:
    """Raw source DDL/type/value expressions without target projection policy."""

    name: str
    pg_ddl: str
    pg_type: str
    seed_sql: str


_SPECS: tuple[tuple[str, str, str, str], ...] = (
    ("id", "INTEGER NOT NULL", "integer", "1"),
    ("business_date", "DATE NOT NULL", "date", "DATE '2026-07-21'"),
    (
        "updated_at",
        "TIMESTAMP WITHOUT TIME ZONE NOT NULL",
        "timestamp without time zone",
        "TIMESTAMP '2026-07-21 10:00:00'",
    ),
    ("c_smallint", "SMALLINT NULL", "smallint", "70"),
    ("c_int2_alias", "INT2 NULL", "int2", "-32768"),
    ("c_smallserial", "SMALLSERIAL NOT NULL", "smallint", "71"),
    ("c_int_alias", "INT NULL", "int", "-2147483648"),
    ("c_int4_alias", "INT4 NULL", "int4", "2147483647"),
    ("c_serial", "SERIAL NOT NULL", "integer", "72"),
    (
        "c_identity",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL",
        "integer",
        "73",
    ),
    ("c_bigint", "BIGINT NULL", "bigint", "7000000000"),
    ("c_int8_alias", "INT8 NULL", "int8", "-9223372036854775808"),
    ("c_bigserial", "BIGSERIAL NOT NULL", "bigint", "74"),
    ("c_decimal", "NUMERIC(18,4) NULL", "numeric(18,4)", "12.3456"),
    ("c_decimal_alias", "DECIMAL(18,4) NULL", "decimal(18,4)", "-12.3456"),
    ("c_numeric_scale_gt_precision", "NUMERIC(3,5) NULL", "numeric(3,5)", "0.00123"),
    ("c_numeric_negative_scale", "NUMERIC(2,-3) NULL", "numeric(2,-3)", "12000"),
    (
        "c_numeric_boundary_38",
        "NUMERIC(38,38) NULL",
        "numeric(38,38)",
        "0.12345678901234567890123456789012345678",
    ),
    ("c_decimal_edge", "NUMERIC(18,4) NULL", "numeric(18,4)", "99999999999999.9999"),
    ("c_bool", "BOOLEAN NULL", "boolean", "TRUE"),
    ("c_bool_alias", "BOOL NULL", "bool", "FALSE"),
    ("c_float", "REAL NULL", "real", "1.25"),
    ("c_float4_alias", "FLOAT4 NULL", "float4", "-3.5"),
    ("c_double", "DOUBLE PRECISION NULL", "double precision", "2.5"),
    ("c_float8_alias", "FLOAT8 NULL", "float8", "9007199254740991.0"),
    ("c_date", "DATE NULL", "date", "DATE '2026-01-15'"),
    (
        "c_datetime",
        "TIMESTAMP WITHOUT TIME ZONE NULL",
        "timestamp without time zone",
        "TIMESTAMP '2026-01-15 12:30:00'",
    ),
    (
        "c_timestamp_alias",
        "TIMESTAMP NULL",
        "timestamp",
        "TIMESTAMP '2026-01-15 12:30:00.123456'",
    ),
    (
        "c_timestamp_scale_0",
        "TIMESTAMP(0) WITHOUT TIME ZONE NULL",
        "timestamp(0) without time zone",
        "TIMESTAMP '2026-01-15 12:30:01'",
    ),
    (
        "c_timestamp_scale_6",
        "TIMESTAMP(6) NULL",
        "timestamp(6)",
        "TIMESTAMP '2026-01-15 12:30:00.654321'",
    ),
    (
        "c_timestamp",
        "TIMESTAMP WITH TIME ZONE NULL",
        "timestamp with time zone",
        "TIMESTAMPTZ '2026-01-15 12:30:00+00'",
    ),
    (
        "c_timestamptz_alias",
        "TIMESTAMPTZ NULL",
        "timestamptz",
        "TIMESTAMPTZ '2026-07-15 02:30:00.123456+03'",
    ),
    (
        "c_timestamptz_scale_3",
        "TIMESTAMPTZ(3) NULL",
        "timestamptz(3)",
        "TIMESTAMPTZ '2026-01-15 12:30:00.123-05:30'",
    ),
    ("c_time", "TIME WITHOUT TIME ZONE NULL", "time without time zone", "TIME '12:30:00'"),
    ("c_time_alias", "TIME NULL", "time", "TIME '12:30:00.123456'"),
    ("c_time_scale_0", "TIME(0) NULL", "time(0)", "TIME '12:30:01'"),
    ("c_varchar", "VARCHAR(255) NULL", "character varying(255)", "'alpha,comma'"),
    ("c_varchar_unbounded", "CHARACTER VARYING NULL", "character varying", "'unbounded Ω'"),
    ("c_varchar_alias_unbounded", "VARCHAR NULL", "varchar", "'alias Ω'"),
    ("c_character_default", "CHARACTER NULL", "character", "'Z'"),
    ("c_char_default", "CHAR NULL", "char", "'Y'"),
    ("c_varchar_2000", "VARCHAR(2000) NULL", "varchar(2000)", "'boundary-2000 Ω'"),
    ("c_character_8", "CHARACTER(8) NULL", "character(8)", "'fixed'"),
    ("c_text", "TEXT NULL", "text", "E'long\\ttext\\nmarker\\x1d unicode Ω'"),
    ("c_empty", "TEXT NULL", "text", "''"),
    ("c_null", "TEXT NULL", "text", "NULL"),
    ("c_json", "JSONB NULL", "jsonb", '\'{"k": 1, "unicode": "Ω"}\'::jsonb'),
    ("c_json_text", "JSON NULL", "json", '\'{"ordered": true, "n": 1}\'::json'),
    ("c_uuid", "UUID NULL", "uuid", "'11111111-1111-1111-1111-111111111111'::uuid"),
    ("c_blob", "BYTEA NULL", "bytea", "'\\x0001ff'::bytea"),
    (
        "c_array",
        "TEXT[] NULL",
        "text[]",
        "ARRAY['alpha', 'comma,value', E'line\\nbreak']::text[]",
    ),
    ("c_range", "INT4RANGE NULL", "int4range", "'[1,8)'::int4range"),
    (
        "c_enum",
        '"__DPONE_ENUM_TYPE__" NULL',
        "my_enum",
        "'alpha'::__DPONE_ENUM_CAST__",
    ),
    ("c_name", "VARCHAR(64) NOT NULL", "character varying(64)", "'row-one'"),
)

# The remaining columns are distinct supported boundary cases.  They make the
# width leg useful as a value-fidelity certification rather than inflating the
# column count with aliases of the same nominal text value.  Unsupported
# values (NaN/Infinity, out-of-range temporals, precision overflow, and
# bounded-text/binary overflow) live in the fail-before-mutation boundary leg.
_SPECS += (
    ("b_smallint_max", "SMALLINT NULL", "smallint", "32767"),
    ("b_smallint_zero", "SMALLINT NULL", "smallint", "0"),
    ("b_integer_zero", "INTEGER NULL", "integer", "0"),
    ("b_bigint_max", "BIGINT NULL", "bigint", "9223372036854775807"),
    ("b_bigint_zero", "BIGINT NULL", "bigint", "0"),
    ("b_numeric_zero", "NUMERIC(18,4) NULL", "numeric(18,4)", "0.0000"),
    ("b_numeric_negative", "NUMERIC(18,4) NULL", "numeric(18,4)", "-99999999999999.9999"),
    ("b_numeric_midpoint_pos", "NUMERIC(6,2) NULL", "numeric(6,2)", "1.235"),
    ("b_numeric_midpoint_neg", "NUMERIC(6,2) NULL", "numeric(6,2)", "-1.235"),
    (
        "b_numeric38_max",
        "NUMERIC(38,0) NULL",
        "numeric(38,0)",
        "99999999999999999999999999999999999999",
    ),
    (
        "b_numeric38_min",
        "NUMERIC(38,0) NULL",
        "numeric(38,0)",
        "-99999999999999999999999999999999999999",
    ),
    ("b_numeric_scale_min", "NUMERIC(5,5) NULL", "numeric(5,5)", "0.00001"),
    ("b_numeric_negative_scale", "NUMERIC(4,-2) NULL", "numeric(4,-2)", "12345"),
    ("b_real_pos_zero", "REAL NULL", "real", "0.0::real"),
    ("b_real_negative_one", "REAL NULL", "real", "'-1'::real"),
    ("b_real_min_normal", "REAL NULL", "real", "'1.17549435e-38'::real"),
    ("b_real_max", "REAL NULL", "real", "'3.40282347e38'::real"),
    ("b_real_min_subnormal", "REAL NULL", "real", "'-1e-45'::real"),
    ("b_float_pos_zero", "DOUBLE PRECISION NULL", "double precision", "0.0::float8"),
    ("b_float_negative_one", "DOUBLE PRECISION NULL", "double precision", "'-1'::float8"),
    (
        "b_float_max",
        "DOUBLE PRECISION NULL",
        "double precision",
        "'1.7976931348623157e308'::float8",
    ),
    (
        "b_float_min_normal",
        "DOUBLE PRECISION NULL",
        "double precision",
        "'2.2250738585072014e-308'::float8",
    ),
    (
        "b_float_near_min_normal",
        "DOUBLE PRECISION NULL",
        "double precision",
        "'2.3e-308'::float8",
    ),
    (
        "b_float_bit_sensitive",
        "DOUBLE PRECISION NULL",
        "double precision",
        "'0.12345678901234567'::float8",
    ),
    ("b_date_min", "DATE NULL", "date", "DATE '0001-01-01'"),
    ("b_date_max", "DATE NULL", "date", "DATE '9999-12-31'"),
    ("b_date_leap", "DATE NULL", "date", "DATE '2000-02-29'"),
    (
        "b_timestamp_min",
        "TIMESTAMP(6) NULL",
        "timestamp(6)",
        "TIMESTAMP '0001-01-01 00:00:00.000000'",
    ),
    (
        "b_timestamp_max",
        "TIMESTAMP(6) NULL",
        "timestamp(6)",
        "TIMESTAMP '9999-12-31 23:59:59.999999'",
    ),
    (
        "b_timestamp_microsecond",
        "TIMESTAMP(6) NULL",
        "timestamp(6)",
        "TIMESTAMP '1970-01-01 00:00:00.000001'",
    ),
    (
        "b_timestamp_pre_epoch",
        "TIMESTAMP(6) NULL",
        "timestamp(6)",
        "TIMESTAMP '1900-01-01 00:00:00.999999'",
    ),
    (
        "b_timestamptz_min",
        "TIMESTAMPTZ(6) NULL",
        "timestamptz(6)",
        "TIMESTAMPTZ '0001-01-01 00:00:00+00'",
    ),
    (
        "b_timestamptz_max",
        "TIMESTAMPTZ(6) NULL",
        "timestamptz(6)",
        "TIMESTAMPTZ '9999-12-31 23:59:59.999999+00'",
    ),
    (
        "b_timestamptz_dst",
        "TIMESTAMPTZ(6) NULL",
        "timestamptz(6)",
        "TIMESTAMPTZ '2026-03-29 01:59:59.999999+01'",
    ),
    (
        "b_timestamptz_offset_plus14",
        "TIMESTAMPTZ(6) NULL",
        "timestamptz(6)",
        "TIMESTAMPTZ '2026-06-01 12:00:00.123456+14'",
    ),
    (
        "b_timestamptz_offset_minus14",
        "TIMESTAMPTZ(6) NULL",
        "timestamptz(6)",
        "TIMESTAMPTZ '2026-06-01 12:00:00.654321-14'",
    ),
    (
        "b_timestamptz_microsecond",
        "TIMESTAMPTZ(6) NULL",
        "timestamptz(6)",
        "TIMESTAMPTZ '1970-01-01 00:00:00.000001+00'",
    ),
    ("b_time_midnight", "TIME(6) NULL", "time(6)", "TIME '00:00:00.000000'"),
    ("b_time_last", "TIME(6) NULL", "time(6)", "TIME '23:59:59.999999'"),
    ("b_time_microsecond", "TIME(6) NULL", "time(6)", "TIME '00:00:00.000001'"),
    ("b_varchar1_empty", "VARCHAR(1) NULL", "varchar(1)", "''"),
    ("b_varchar1_unicode", "VARCHAR(1) NULL", "varchar(1)", "'Ω'"),
    ("b_varchar_control", "VARCHAR(4) NULL", "varchar(4)", "E'\\t\\n\\rX'"),
    ("b_varchar_trailing", "VARCHAR(8) NULL", "varchar(8)", "'x   '"),
    ("b_character_padded", "CHARACTER(8) NULL", "character(8)", "'x'"),
    ("b_character_exact", "CHARACTER(8) NULL", "character(8)", "'12345678'"),
    ("b_text_marker_empty", "TEXT NULL", "text", "E'\\x1dE'"),
    ("b_text_marker_null", "TEXT NULL", "text", "E'\\x1dN'"),
    ("b_text_controls", "TEXT NULL", "text", "E'\\x01\\t\\n\\r\\x1d'"),
    ("b_text_supplementary", "TEXT NULL", "text", "'😀🚀𝔘́'"),
    ("b_text_combining", "TEXT NULL", "text", "U&'A\\0301|\\00C1|\\03A9'"),
    ("b_text_case_accent", "TEXT NULL", "text", "'A|a|Á|á|Ａ|ａ'"),
    ("b_text_large", "TEXT NULL", "text", "repeat('Ω', 8192)"),
    ("b_varchar2000_ascii", "VARCHAR(2000) NULL", "varchar(2000)", "repeat('x', 2000)"),
    ("b_varchar2000_unicode", "VARCHAR(2000) NULL", "varchar(2000)", "repeat('😀', 2000)"),
    ("b_json_empty_object", "JSON NULL", "json", "'{}'::json"),
    ("b_json_array", "JSON NULL", "json", "'[null,\"\\u03a9\",1]'::json"),
    ("b_jsonb_nested", "JSONB NULL", "jsonb", '\'{"a":[1,null,{"b":true}]}\'::jsonb'),
    ("b_uuid_zero", "UUID NULL", "uuid", "'00000000-0000-0000-0000-000000000000'::uuid"),
    ("b_uuid_max", "UUID NULL", "uuid", "'ffffffff-ffff-ffff-ffff-ffffffffffff'::uuid"),
    ("b_bytea_empty", "BYTEA NULL", "bytea", "'\\x'::bytea"),
    ("b_bytea_nul", "BYTEA NULL", "bytea", "'\\x00'::bytea"),
    (
        "b_bytea_all_values",
        "BYTEA NULL",
        "bytea",
        "decode((SELECT string_agg(lpad(to_hex(v), 2, '0'), '' ORDER BY v) FROM generate_series(0,255) v), 'hex')",
    ),
    ("b_bytea_large", "BYTEA NULL", "bytea", "decode(repeat('ab', 8192), 'hex')"),
    ("b_array_empty", "TEXT[] NULL", "text[]", "ARRAY[]::text[]"),
    ("b_array_null_element", "TEXT[] NULL", "text[]", "ARRAY['a', NULL, '']::text[]"),
    (
        "b_array_multidimensional",
        "TEXT[][] NULL",
        "text[]",
        "ARRAY[[E'a,b', E'line\\nbreak'], [NULL, E'\\x1dE']]::text[][]",
    ),
    (
        "b_array_non_one_lower_bound",
        "TEXT[] NULL",
        "text[]",
        "'[0:2]={alpha,NULL,omega}'::text[]",
    ),
    ("b_range_empty", "INT4RANGE NULL", "int4range", "'empty'::int4range"),
    ("b_range_unbounded", "INT4RANGE NULL", "int4range", "'(,)'::int4range"),
    ("b_range_canonicalized", "INT4RANGE NULL", "int4range", "'(1,8]'::int4range"),
    ("b_enum_beta", '"__DPONE_ENUM_TYPE__" NULL', "my_enum", "'beta'::__DPONE_ENUM_CAST__"),
    ("b_bool_true", "BOOLEAN NULL", "boolean", "TRUE"),
    ("b_bool_false", "BOOLEAN NULL", "boolean", "FALSE"),
)

assert len(_SPECS) == WIDE_COLUMN_TARGET, (
    f"wide fixture must contain exactly {WIDE_COLUMN_TARGET} semantic columns, got {len(_SPECS)}"
)


def postgres_fixture_columns() -> tuple[PostgresFixtureColumn, ...]:
    """Return every immutable source column in its original semantic order."""
    return tuple(PostgresFixtureColumn(*spec) for spec in _SPECS)
