"""Required repository-local files and terms for agent setup validation."""

from __future__ import annotations

MAX_INSTRUCTION_BYTES = 32 * 1024
SKILL_NAME_PATTERN = r"^[a-z0-9]+(?:-[a-z0-9]+)*$"

REQUIRED_FILES = (
    "AGENTS.md",
    ".codex/config.toml",
    "src/dpone/AGENTS.md",
    "tests/AGENTS.md",
    "docs/AGENTS.md",
    "packages/dpone-airflow-pack/AGENTS.md",
    "docs/engineering-standards.md",
    "docs/feature-design-standard.md",
    "docs/documentation-standard.md",
    "docs/agent-development.md",
    "docs/agent-governance.md",
    "docs/agent-pr-merge-receipt-runbook.md",
    "docs/agent-mcp-connectors.md",
    "docs/agent-permissions.md",
    "docs/agent-release-protocol.md",
    "docs/agent-task-contracts.md",
    "docs/agent-risk-register.md",
    "docs/agent-security-mapping.md",
    "docs/feature-design-agent-task-contract-gate.md",
    "docs/feature-design-agent-permission-tool-registry.md",
    "docs/feature-design-mcp-connector-onboarding-gate.md",
    "docs/agent-templates/feature-design-spec.md",
    "docs/agent-templates/agent-task-contract.yml",
    "docs/agent-templates/release-evidence-report.md",
    "docs/github-branch-protection.md",
    "docs/supply-chain-slsa.md",
    ".github/ISSUE_TEMPLATE/admin_bypass.yml",
    ".github/ISSUE_TEMPLATE/feature_design.yml",
    ".github/ISSUE_TEMPLATE/release_readiness.yml",
    ".github/workflows/dependency-review.yml",
    ".github/codex/prompts/review.md",
    ".github/pull_request_template.md",
    ".github/CODEOWNERS",
    ".worktreeinclude",
    "CONTRIBUTING.md",
    ".agents/policy/agent-permission-profile.yml",
    ".agents/policy/github-branch-protection.yml",
    ".agents/policy/mcp-connector-onboarding.yml",
    ".agents/policy/tool-registry.yml",
    ".agents/policy/workflow-security.yml",
    ".agents/policy/workflow-security-privileged.yml",
    ".agents/policy/workflow-security-privileged-v2.yml",
    ".agents/policy/workflow-security-privileged-v3.yml",
    "evals/agent/agent-permission-profile.schema.json",
    "evals/agent/agent-task-contract.schema.json",
    "evals/agent/audit-manifest.schema.json",
    "evals/agent/github-branch-protection.schema.json",
    "evals/agent/result.schema.json",
    "evals/agent/governance-gate.schema.json",
    "evals/agent/governance-drift-summary.schema.json",
    "evals/agent/mcp-connector-onboarding.schema.json",
    "evals/agent/pr-merge-receipt.schema.json",
    "evals/agent/pr-receipt.schema.json",
    "evals/agent/tool-registry.schema.json",
    "evals/agent/workflow-security.schema.json",
    "evals/agent/workflow-security-privileged-policy.schema.json",
    "evals/agent/workflow-security-privileged-policy-v2.schema.json",
    "evals/agent/workflow-security-privileged-policy-v3.schema.json",
    "evals/agent/workflow-security-privileged-report.schema.json",
    "evals/agent/red_team_scenarios.yml",
    "tools/agent_policy/audit_manifest.py",
    "tools/agent_policy/branch_protection.py",
    "tools/agent_policy/control_surface.py",
    "tools/agent_policy/github_settings_drift.py",
    "tools/agent_policy/governance_artifact_archive.py",
    "tools/agent_policy/governance_artifact_attestation.py",
    "tools/agent_policy/governance_artifact_content.py",
    "tools/agent_policy/governance_drift_summary.py",
    "tools/agent_policy/governance_checks.py",
    "tools/agent_policy/governance_gate.py",
    "tools/agent_policy/governance_standards.py",
    "tools/agent_policy/mcp_onboarding.py",
    "tools/agent_policy/permission_profiles.py",
    "tools/agent_policy/permissions.py",
    "tools/agent_policy/policy_constants.py",
    "tools/agent_policy/policy_support.py",
    "tools/agent_policy/pr_body.py",
    "tools/agent_policy/pr_merge_check.py",
    "tools/agent_policy/pr_merge_binding.py",
    "tools/agent_policy/pr_merge_identity.py",
    "tools/agent_policy/pr_merge_receipt.py",
    "tools/agent_policy/pr_merge_receipt_contract.py",
    "tools/agent_policy/release_merge_receipt_gate.py",
    "tools/agent_policy/release_merge_receipt_reconcile.py",
    "tools/agent_policy/path_evidence.py",
    "tools/agent_policy/pr_receipt.py",
    "tools/agent_policy/pr_receipt_wait.py",
    "tools/agent_policy/pr_receipt_github.py",
    "tools/agent_policy/pr_receipt_github_attestation.py",
    "tools/agent_policy/pr_receipt_github_validation.py",
    "tools/agent_policy/pr_receipt_source.py",
    "tools/agent_policy/pr_receipt_source_archive.py",
    "tools/agent_policy/pr_traceability.py",
    "tools/agent_policy/red_team.py",
    "tools/agent_policy/setup_inventory.py",
    "tools/agent_policy/supply_chain_checks.py",
    "tools/agent_policy/task_contract.py",
    "tools/agent_policy/tool_registry.py",
    "tools/agent_policy/workflow_artifacts.py",
    "tools/agent_policy/workflow_security.py",
    "tools/agent_policy/workflow_privilege_contracts.py",
    "tools/agent_policy/workflow_privilege_composition.py",
    "tools/agent_policy/workflow_privilege_snapshot.py",
    "tools/agent_policy/workflow_privilege_policy_selection.py",
    "tools/agent_policy/workflow_privilege_parser.py",
    "tools/agent_policy/workflow_privilege_graph.py",
    "tools/agent_policy/workflow_privilege_expressions.py",
    "tools/agent_policy/workflow_privilege_permissions.py",
    "tools/agent_policy/workflow_privilege_profiles.py",
    "tools/agent_policy/workflow_privilege_profile_support.py",
    "tools/agent_policy/workflow_privilege_report.py",
    "tools/agent_policy/workflow_privilege_service.py",
    "tools/agent_policy/workflow_security_privileged.py",
    ".github/workflows/agent-governance-drift.yml",
    ".github/workflows/agent-pr-receipt.yml",
)

REQUIRED_RED_TEAM_SCENARIOS = (
    "connector scope escalation",
    "prompt injection",
    "secret disclosure",
    "workflow tampering",
    "verification laundering",
    "excessive agency",
    "unbounded consumption",
    "unregistered tool use",
    "github settings drift",
)

RED_TEAM_DOCS = (
    "docs/agent-governance.md",
    "docs/agent-risk-register.md",
    "docs/agent-security-mapping.md",
)

NESTED_INSTRUCTIONS = (
    "src/dpone/AGENTS.md",
    "tests/AGENTS.md",
    "docs/AGENTS.md",
    "packages/dpone-airflow-pack/AGENTS.md",
)
