"""Stable machine-readable codes for launch-pin failures."""

from __future__ import annotations

PIN_INVALID = "DPONE_AIRFLOW_DEPLOYMENT_IDENTITY_PIN_INVALID"
PIN_UNAVAILABLE = "DPONE_AIRFLOW_DEPLOYMENT_IDENTITY_PIN_UNAVAILABLE"
PIN_MISSING = "DPONE_AIRFLOW_DEPLOYMENT_IDENTITY_PIN_MISSING"
PIN_CONFLICT = "DPONE_AIRFLOW_DEPLOYMENT_IDENTITY_PIN_CONFLICT"
PIN_STALE_WRITER = "DPONE_AIRFLOW_DEPLOYMENT_IDENTITY_PIN_STALE_WRITER"
PIN_RECOVERY_REQUIRED = "DPONE_AIRFLOW_DEPLOYMENT_IDENTITY_PIN_RECOVERY_REQUIRED"

LAUNCH_PIN_STATE_CANDIDATE = "CANDIDATE"
LAUNCH_PIN_STATE_ACTIVE = "ACTIVE"
LAUNCH_PIN_STATE_CONSUMED = "CONSUMED"

# Head transition / release statuses that prove closure before per-try delete.
HEAD_PROVEN_CLOSED_STATUSES = frozenset({"consumed", "already_consumed", "deleted", "absent"})

__all__ = [
    "LAUNCH_PIN_STATE_ACTIVE",
    "LAUNCH_PIN_STATE_CANDIDATE",
    "LAUNCH_PIN_STATE_CONSUMED",
    "HEAD_PROVEN_CLOSED_STATUSES",
    "PIN_CONFLICT",
    "PIN_INVALID",
    "PIN_MISSING",
    "PIN_RECOVERY_REQUIRED",
    "PIN_STALE_WRITER",
    "PIN_UNAVAILABLE",
]
