"""Stable activation codes for MSSQL outlet projection failures."""

from __future__ import annotations

MSSQL_ASSET_OUTLET_PROJECTION_SCHEMA = "dpone.mssql-asset-outlet-projection.v1"
PROJECTION_REQUIRED = "DPONE_MSSQL_ASSET_OUTLET_PROJECTION_REQUIRED"
PROJECTION_INVALID = "DPONE_MSSQL_ASSET_OUTLET_PROJECTION_INVALID"
PROJECTION_MISMATCH = "DPONE_MSSQL_ASSET_OUTLET_PROJECTION_MISMATCH"

__all__ = [
    "MSSQL_ASSET_OUTLET_PROJECTION_SCHEMA",
    "PROJECTION_INVALID",
    "PROJECTION_MISMATCH",
    "PROJECTION_REQUIRED",
]
