name: dpone_dbt_demo
version: 1.0.0
config-version: 2
profile: dpone_dbt_demo
model-paths: ["models"]

flags:
  dbt_sqlserver_enable_safe_type_expansion: false
  dbt_sqlserver_use_native_string_types: true
  dbt_sqlserver_use_dbt_transactions: true
  dbt_sqlserver_use_default_schema_concat: true

models:
  dpone_dbt_demo:
    +database: DWH_Stage
    +schema: pricing
    +as_columnstore: false
    +indexes: []
    +drop_unmanaged_indexes: false
    +prefer_single_alter_column: false
    +group: pricing
    +meta:
      dpone:
        publish:
          enabled: true
          profile: mssql_to_clickhouse_mart
          workflow: competitive_pricing
