"""Materialize authoring sources into canonical runtime manifest IR."""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from dpone.manifest.authoring import AuthoringCompilationError, default_authoring_compiler
from dpone.manifest.bounded_yaml import BoundedYamlError, BoundedYamlLimits, load_bounded_yaml
from dpone.manifest.confined_files import ConfinedFileError, read_confined_file

_MANIFEST_LIMITS = BoundedYamlLimits(max_bytes=8 * 1024 * 1024, max_tokens=100_000, max_nodes=50_000)


class RuntimeManifestMaterializationError(ValueError):
    """An editable manifest cannot be compiled into safe runtime input."""

    def __init__(self, message: str, *, code: str | None = None) -> None:
        super().__init__(message)
        self.code = code


@dataclass(frozen=True, slots=True)
class RuntimeManifestMaterialization:
    """Runtime target and optional generated bytes embedded into a workload."""

    path: str
    sha256: str | None
    kind: str
    content: bytes | None = None

    def to_jsonable(self) -> dict[str, str | None]:
        return {"path": self.path, "sha256": self.sha256, "kind": self.kind}


def materialize_runtime_manifest(
    *,
    workload_id: str,
    manifest: str,
    repo_root: Path | None,
) -> RuntimeManifestMaterialization:
    """Compile editable authoring to canonical IR; preserve canonical inputs."""

    if repo_root is None:
        return RuntimeManifestMaterialization(path=manifest, sha256=None, kind="unmaterialized_manifest")
    root = repo_root.resolve(strict=True)
    try:
        source_bytes = read_confined_file(root, manifest, max_bytes=_MANIFEST_LIMITS.max_bytes)
        source_ref = PurePosixPath(manifest)
        source_path = root.joinpath(*source_ref.parts)
        payload = load_bounded_yaml(source_bytes, limits=_MANIFEST_LIMITS)
    except (BoundedYamlError, ConfinedFileError) as exc:
        raise RuntimeManifestMaterializationError("runtime_manifest_read_failed") from exc
    if not isinstance(payload, Mapping) or not _is_authoring_source(payload):
        return RuntimeManifestMaterialization(
            path=manifest,
            sha256=_sha256(source_bytes),
            kind="source_manifest",
        )
    try:
        compilation = default_authoring_compiler().compile(
            payload,
            source_path=source_path,
            project_root=root,
        )
    except AuthoringCompilationError as exc:
        if exc.code == "DPONE_AIRFLOW_RESOURCES_INVALID":
            raise RuntimeManifestMaterializationError(str(exc), code=exc.code) from exc
        raise RuntimeManifestMaterializationError("runtime_manifest_compile_failed") from exc
    canonical_bytes = (
        json.dumps(compilation.canonical_manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    ).encode("utf-8")
    safe_id = "".join(char if char.isalnum() or char in {"_", "-"} else "_" for char in workload_id)
    runtime_path = (source_ref.parent / f".{safe_id}.dpone.batch.json").as_posix()
    return RuntimeManifestMaterialization(
        path=runtime_path,
        sha256=_sha256(canonical_bytes),
        kind="canonical_manifest",
        content=canonical_bytes,
    )


def _is_authoring_source(payload: Mapping[str, Any]) -> bool:
    kind = str(payload.get("kind") or payload.get("schema") or "").strip()
    return kind in {"dpone.flow.v1", "dpone.pipeline.v1"} or (
        kind == "dpone.batch.v1" and "processes" in payload and "schemas" not in payload
    )


def _sha256(payload: bytes) -> str:
    return "sha256:" + hashlib.sha256(payload).hexdigest()


__all__ = [
    "RuntimeManifestMaterialization",
    "RuntimeManifestMaterializationError",
    "materialize_runtime_manifest",
]
