[mypy]
python_version = 3.11
files =
    src/dpone/app,
    src/dpone/ports,
    src/dpone/adapters,
    src/dpone/commands,
    src/dpone/services,
    src/dpone/manifest,
    src/dpone/dag,
    src/dpone/metrics,
    packages/dpone-airflow-pack/src/dpone_airflow_pack,
    packages/apache-airflow-providers-dpone/src/airflow/providers/dpone
ignore_missing_imports = True
follow_imports = silent
show_error_codes = True
pretty = True
warn_unused_ignores = True
no_implicit_optional = True
check_untyped_defs = True
