"""Synthetic, independently frozen scalar oracle; never live certification.

Vectors are hand-specified native field bytes, not generated by dpone's encoder
or decoder. Typed multiset keys retain IEEE float bits, text length/content and
microseconds, so ordinary equality cannot hide signed-zero or duplicate loss.
"""

from collections import Counter
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from struct import pack
from uuid import UUID


@dataclass(frozen=True)
class ScalarVector:
    """One admitted ClickHouse/MSSQL intersection with a frozen wire field."""

    name: str
    source_type: str
    target_type: str
    source_value: object
    expected_value: object
    native_hex: str


VECTORS = (
    ScalarVector("int64-min", "Int64", "bigint", -(2**63), -(2**63), "0000000000000080"),
    ScalarVector("int64-max", "Int64", "bigint", 2**63 - 1, 2**63 - 1, "ffffffffffffff7f"),
    ScalarVector("int8-min", "Int8", "smallint", -128, -128, "80ff"),
    ScalarVector("int16-min", "Int16", "smallint", -32768, -32768, "0080"),
    ScalarVector("int32-min", "Int32", "int", -(2**31), -(2**31), "00000080"),
    ScalarVector("uint16-max", "UInt16", "int", 65535, 65535, "ffff0000"),
    ScalarVector("uint32-max", "UInt32", "bigint", 2**32 - 1, 2**32 - 1, "ffffffff00000000"),
    ScalarVector("uint8-max", "UInt8", "tinyint", 255, 255, "ff"),
    ScalarVector(
        "uint64-max",
        "UInt64",
        "decimal(20,0)",
        2**64 - 1,
        Decimal("18446744073709551615"),
        "13140001ffffffffffffffff0000000000000000",
    ),
    ScalarVector(
        "decimal-negative",
        "Decimal(5,2)",
        "decimal(5,2)",
        Decimal("-999.99"),
        Decimal("-999.99"),
        "130502009f860100000000000000000000000000",
    ),
    ScalarVector("float64-positive-zero", "Float64", "float", 0.0, 0.0, "0000000000000000"),
    ScalarVector("float64-negative-zero", "Float64", "float", -0.0, -0.0, "0000000000000080"),
    ScalarVector("float64-subnormal", "Float64", "float", 2.0**-1074, 2.0**-1074, "0100000000000000"),
    ScalarVector("float32-negative-zero", "Float32", "real", -0.0, -0.0, "00000080"),
    ScalarVector("float32-subnormal", "Float32", "real", 2.0**-149, 2.0**-149, "01000000"),
    ScalarVector("false", "Bool", "bit", False, False, "0100"),
    ScalarVector("true", "Bool", "bit", True, True, "0101"),
    ScalarVector("null", "Nullable(Int32)", "int nullable", None, None, "ff"),
    ScalarVector("empty", "String", "nvarchar(max)", b"", "", "0000000000000000"),
    ScalarVector(
        "nul-unicode-spaces",
        "String",
        "nvarchar(max)",
        "A\x00😀é  ".encode(),
        "A\x00😀é  ",
        "0e00000000000000410000003dd800dee90020002000",
    ),
    ScalarVector("date", "Date32", "date", date(1970, 1, 1), date(1970, 1, 1), "3af90a"),
    ScalarVector(
        "microsecond", "DateTime64(6)", "datetime2(6)", 1, datetime(1970, 1, 1, microsecond=1), "0a000000003af90a"
    ),
    ScalarVector(
        "uuid",
        "UUID",
        "uniqueidentifier",
        UUID("00112233-4455-6677-8899-aabbccddeeff"),
        "00112233-4455-6677-8899-aabbccddeeff",
        "1033221100554477668899aabbccddeeff",
    ),
)


def scalar_key(value):
    """Canonical exact key independent of all production digest code."""
    if isinstance(value, float):
        return ("float64-bits", pack(">d", value).hex())
    if isinstance(value, datetime):
        return ("datetime", value.isoformat(timespec="microseconds"))
    if isinstance(value, Decimal):
        return ("decimal", str(value))
    return (type(value).__name__, value)


def scalar_multiset(values):
    """Count every scalar occurrence, preserving distinctions such as ±0."""
    return Counter(scalar_key(value) for value in values)
