from __future__ import annotations

from pathlib import Path

from dpone.cli.parser import build_parser
from dpone.gitops.schema_contracts import gitops_schema_contracts
from dpone.services.docs.cli_reference import render_cli_reference_block
from dpone.services.docs.gitops_schema_reference import (
    GITOPS_SCHEMA_REF_END,
    GITOPS_SCHEMA_REF_START,
    _render_required,
    is_gitops_schema_reference_doc_in_sync,
    render_gitops_schema_reference_block,
    sync_gitops_schema_reference_doc,
)


def test_render_gitops_schema_reference_is_generated_from_registered_contracts() -> None:
    rendered = render_gitops_schema_reference_block()

    assert GITOPS_SCHEMA_REF_START in rendered
    assert GITOPS_SCHEMA_REF_END in rendered
    assert "_This section is auto-generated by `dpone docs update-gitops-schema-reference`._" in rendered
    assert f"Registered contracts: **{len(gitops_schema_contracts())}**." in rendered
    assert "`dpone gitops schema list --prefix dpone.safe-sample`" in rendered
    assert (
        "`dpone gitops schema validate --kind dpone.safe-sample-runtime-run.v1 --payload runtime-run.json`" in rendered
    )
    assert (
        "| `release-set` | `dpone.release-set.v1` | "
        "[schema](https://paulkov.github.io/dpone/schemas/gitops/release-set.schema.json) |" in rendered
    )
    assert (
        "| `safe-sample-runtime-run` | `dpone.safe-sample-runtime-run.v1` | "
        "[schema](https://paulkov.github.io/dpone/schemas/gitops/safe-sample-runtime-run.schema.json) |" in rendered
    )
    assert (
        "`deployment-cache-retention-apply-v3`" in rendered
        and "conditional: `activation_history_revision`, `operation_id`, `receipt_revision`, `review_id`, "
        "`reviewed_plan_sha256`, `transaction_status`"
        in rendered
    )


def test_gitops_schema_reference_sync_roundtrip(tmp_path: Path) -> None:
    doc = tmp_path / "gitops-schema-catalog.md"
    doc.write_text(
        f"# GitOps schema catalog\n\n{GITOPS_SCHEMA_REF_START}\nold\n{GITOPS_SCHEMA_REF_END}\n",
        encoding="utf-8",
    )

    changed, _ = sync_gitops_schema_reference_doc(doc)

    assert changed is True
    assert is_gitops_schema_reference_doc_in_sync(doc) is True


def test_conditional_requirements_render_without_unconditional_fields() -> None:
    rendered = _render_required(
        {
            "allOf": [
                {
                    "if": {"properties": {"status": {"const": "committed"}}},
                    "then": {"required": ["operation_id", "receipt_revision"]},
                }
            ]
        }
    )

    assert rendered == "conditional: `operation_id`, `receipt_revision`"


def test_cli_reference_contains_gitops_schema_reference_update_command() -> None:
    rendered = render_cli_reference_block(build_parser())

    assert "dpone docs update-gitops-schema-reference" in rendered
