from __future__ import annotations

import json
from pathlib import Path

from dpone.ops.route_rc_executor import RouteReleaseCandidateExecutorService
from dpone.ops.routes.models import RouteKey
from dpone.ops.routes.rc_executor_runner import CommandProcessResult


class _RecordingRunner:
    def __init__(
        self,
        *,
        results: tuple[CommandProcessResult, ...] = (),
        artifacts: tuple[Path, ...] = (),
    ) -> None:
        self.calls: list[tuple[str, int]] = []
        self._results = list(results)
        self._artifacts = list(artifacts)

    def run(self, command: str, *, cwd: Path | None, timeout_seconds: int) -> CommandProcessResult:
        self.calls.append((command, timeout_seconds))
        if self._artifacts:
            artifact = self._artifacts.pop(0)
            artifact.parent.mkdir(parents=True, exist_ok=True)
            artifact.write_text('{"passed": true, "summary": "generated by fake runner"}\n', encoding="utf-8")
        if self._results:
            return self._results.pop(0)
        return CommandProcessResult(exit_code=0, stdout="ok", stderr="", duration_seconds=0.01)


def _write_orchestration(path: Path, *, route: RouteKey | None = None) -> Path:
    route = route or RouteKey.of("mssql", "clickhouse", "incremental_merge")
    base = path.parent / "rc"
    steps = [
        _step("route_certification_pack", "uv run dpone ops route-certification-pack --token keep-me-secret", base),
        _step("route_live_certification", "uv run dpone ops route-live-certification", base),
        _step("route_release_gate", "uv run dpone ops route-release-gate", base),
        _step("release_evidence_pack", "uv run dpone ops release-evidence-pack", base),
    ]
    payload = {
        "schema_version": "dpone.route_rc_orchestrator.v1",
        "release": "0.8.0-rc1",
        "profile": "local_live",
        "row_count": 10000,
        "route": route.to_dict(),
        "route_profile": None,
        "passed": True,
        "level": "release_ready",
        "score": 100.0,
        "blockers": [],
        "warnings": [],
        "next_actions": [],
        "steps": steps,
        "artifact_index": {step["name"]: step["path"] for step in steps},
        "output_dir": str(base),
        "json_path": str(path),
        "markdown_path": str(path.with_suffix(".md")),
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def _step(name: str, command: str, base: Path) -> dict[str, object]:
    artifact = base / name / f"{name}.json"
    return {
        "name": name,
        "command": command,
        "path": str(artifact),
        "sha256": "0" * 64,
        "passed": True,
        "required": True,
        "summary": f"{name} planned",
        "blockers": [],
    }


def _artifact_paths(orchestration_json: Path) -> tuple[Path, ...]:
    payload = json.loads(orchestration_json.read_text(encoding="utf-8"))
    return tuple(Path(step["path"]) for step in payload["steps"])


def test_route_rc_executor_dry_run_plans_without_running_commands(tmp_path: Path) -> None:
    orchestration_json = _write_orchestration(tmp_path / "orchestration" / "route_rc_orchestration.json")
    runner = _RecordingRunner()

    report = RouteReleaseCandidateExecutorService(command_runner=runner).execute(
        orchestration_json=orchestration_json,
        output_dir=tmp_path / "execution",
        execute=False,
        timeout_seconds=7,
        max_attempts=2,
        extra_redactions=("keep-me-secret",),
    )
    payload = json.loads(Path(report.json_path).read_text(encoding="utf-8"))

    assert runner.calls == []
    assert report.passed is True
    assert payload["schema_version"] == "dpone.route_rc_executor.v1"
    assert payload["mode"] == "dry_run"
    assert payload["executed"] is False
    assert payload["route"]["case_id"] == "mssql_to_clickhouse__incremental_merge"
    assert {step["status"] for step in payload["steps"]} == {"planned"}
    assert all(step["attempts"] == 0 for step in payload["steps"])
    assert "keep-me-secret" not in json.dumps(payload)
    assert Path(payload["markdown_path"]).exists()


def test_route_rc_executor_execute_runs_steps_collects_artifacts_and_redacts_logs(tmp_path: Path) -> None:
    orchestration_json = _write_orchestration(tmp_path / "orchestration" / "route_rc_orchestration.json")
    artifacts = _artifact_paths(orchestration_json)
    runner = _RecordingRunner(
        results=(
            CommandProcessResult(
                exit_code=0,
                stdout="TOKEN=keep-me-secret PASSWORD=s3cr3t",
                stderr="secret=another-secret",
                duration_seconds=0.02,
            ),
            CommandProcessResult(exit_code=0, stdout="ok", stderr="", duration_seconds=0.02),
            CommandProcessResult(exit_code=0, stdout="ok", stderr="", duration_seconds=0.02),
            CommandProcessResult(exit_code=0, stdout="ok", stderr="", duration_seconds=0.02),
        ),
        artifacts=artifacts,
    )

    report = RouteReleaseCandidateExecutorService(command_runner=runner).execute(
        orchestration_json=orchestration_json,
        output_dir=tmp_path / "execution",
        execute=True,
        timeout_seconds=9,
        max_attempts=1,
        extra_redactions=("keep-me-secret", "another-secret"),
    )
    payload = json.loads(Path(report.json_path).read_text(encoding="utf-8"))

    assert report.passed is True
    assert payload["mode"] == "execute"
    assert payload["executed"] is True
    assert len(runner.calls) == 4
    assert all(timeout == 9 for _, timeout in runner.calls)
    assert {step["status"] for step in payload["steps"]} == {"passed"}
    assert all(item["exists"] is True for item in payload["artifacts"])
    assert all(item["sha256"] != "0" * 64 for item in payload["artifacts"])
    serialized = json.dumps(payload)
    assert "keep-me-secret" not in serialized
    assert "s3cr3t" not in serialized
    assert "another-secret" not in serialized
    assert "[REDACTED]" in serialized


def test_route_rc_executor_fails_closed_for_nonzero_exit(tmp_path: Path) -> None:
    orchestration_json = _write_orchestration(tmp_path / "orchestration" / "route_rc_orchestration.json")
    runner = _RecordingRunner(
        results=(CommandProcessResult(exit_code=17, stdout="", stderr="boom", duration_seconds=0.01),)
    )

    report = RouteReleaseCandidateExecutorService(command_runner=runner).execute(
        orchestration_json=orchestration_json,
        output_dir=tmp_path / "execution",
        execute=True,
    )

    assert report.passed is False
    assert report.level == "blocked"
    assert "route_certification_pack.command_failed" in report.blockers


def test_route_rc_executor_fails_closed_for_missing_required_artifacts(tmp_path: Path) -> None:
    orchestration_json = _write_orchestration(tmp_path / "orchestration" / "route_rc_orchestration.json")
    runner = _RecordingRunner(
        results=(
            CommandProcessResult(exit_code=0, stdout="ok", stderr="", duration_seconds=0.01),
            CommandProcessResult(exit_code=0, stdout="ok", stderr="", duration_seconds=0.01),
            CommandProcessResult(exit_code=0, stdout="ok", stderr="", duration_seconds=0.01),
            CommandProcessResult(exit_code=0, stdout="ok", stderr="", duration_seconds=0.01),
        )
    )

    report = RouteReleaseCandidateExecutorService(command_runner=runner).execute(
        orchestration_json=orchestration_json,
        output_dir=tmp_path / "execution",
        execute=True,
    )

    assert report.passed is False
    assert "route_certification_pack.artifact_missing" in report.blockers


def test_route_rc_executor_resolves_relative_artifact_paths_from_orchestration_dir(tmp_path: Path) -> None:
    orchestration_json = _write_orchestration(tmp_path / "orchestration" / "route_rc_orchestration.json")
    payload = json.loads(orchestration_json.read_text(encoding="utf-8"))
    payload["steps"][0]["path"] = "rc/route_certification_pack/route_certification_pack.json"
    payload["artifact_index"]["route_certification_pack"] = payload["steps"][0]["path"]
    orchestration_json.write_text(json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True), encoding="utf-8")

    report = RouteReleaseCandidateExecutorService(command_runner=_RecordingRunner()).execute(
        orchestration_json=orchestration_json,
        output_dir=tmp_path / "execution",
    )
    receipt = json.loads(Path(report.json_path).read_text(encoding="utf-8"))

    expected = orchestration_json.parent / "rc" / "route_certification_pack" / "route_certification_pack.json"
    artifacts = {item["name"]: item["path"] for item in receipt["artifacts"]}
    assert receipt["steps"][0]["path"] == str(expected)
    assert artifacts["route_certification_pack"] == str(expected)
