from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest
from tools.airflow_constraints_override import (
    EVIDENCE_SCHEMA,
    derive_provider_override_constraints,
    main,
)


def _sha256(payload: bytes) -> str:
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def test_derivation_removes_only_the_named_exact_pin() -> None:
    source = (
        b"# generated by Apache Airflow\n"
        b"apache-airflow==3.3.0\n"
        b"apache_airflow_providers_cncf_kubernetes==10.19.0\n"
        b"kubernetes==32.0.1  # unchanged byte-for-byte\n"
    )

    derived, evidence = derive_provider_override_constraints(
        source,
        distribution="apache-airflow-providers-cncf-kubernetes",
        requested_version="10.20.0",
    )

    assert derived == (
        b"# generated by Apache Airflow\napache-airflow==3.3.0\nkubernetes==32.0.1  # unchanged byte-for-byte\n"
    )
    assert evidence == {
        "schema": EVIDENCE_SCHEMA,
        "status": "PASS",
        "distribution": "apache-airflow-providers-cncf-kubernetes",
        "constrained_version": "10.19.0",
        "requested_version": "10.20.0",
        "removed_requirement": ("apache_airflow_providers_cncf_kubernetes==10.19.0"),
        "source_sha256": _sha256(source),
        "derived_sha256": _sha256(derived),
        "preserved_line_count": 3,
    }


@pytest.mark.parametrize(
    "source, expected_count",
    [
        (b"apache-airflow==3.3.0\n", 0),
        (
            b"apache-airflow-providers-cncf-kubernetes==10.19.0\napache_airflow_providers_cncf_kubernetes==10.19.0\n",
            2,
        ),
    ],
)
def test_derivation_fails_closed_when_named_pin_is_not_unique(
    source: bytes,
    expected_count: int,
) -> None:
    with pytest.raises(ValueError, match=f"found {expected_count}"):
        derive_provider_override_constraints(
            source,
            distribution="apache-airflow-providers-cncf-kubernetes",
            requested_version="10.20.0",
        )


def test_cli_writes_digest_bound_evidence(tmp_path: Path) -> None:
    source = tmp_path / "constraints.txt"
    output = tmp_path / "install-constraints.txt"
    evidence_path = tmp_path / "override.json"
    source.write_bytes(b"apache-airflow-providers-cncf-kubernetes==10.19.0\nfoo==1.0\n")

    status = main(
        [
            "--source",
            str(source),
            "--output",
            str(output),
            "--distribution",
            "apache-airflow-providers-cncf-kubernetes",
            "--requested-version",
            "10.20.0",
            "--evidence",
            str(evidence_path),
        ]
    )

    assert status == 0
    assert output.read_bytes() == b"foo==1.0\n"
    evidence = json.loads(evidence_path.read_text(encoding="utf-8"))
    assert evidence["status"] == "PASS"
    assert evidence["derived_sha256"] == _sha256(output.read_bytes())
