"""Fixed synthetic R1 wire-format and fail-closed regression vectors.

The scalar vector combines eleven types, negative-zero normalization, an epoch
boundary, a NULL marker and raw bytes. Golden bytes protect compatibility across
source/Python/target hashing; they are not generated by the implementation here.
"""

from __future__ import annotations

from datetime import UTC, date, datetime, time
from decimal import Decimal
from uuid import UUID

import pytest

from dpone.contracts.postgres_mssql_hash_policy import (
    R1Column,
    R1HashContractError,
    R1ScalarType,
    artifact_digest,
    artifact_set_digest,
    canonical_key_payload,
    canonical_row_bytes,
    canonical_row_hash,
)


def test_scalar_row_hash_golden_vector() -> None:
    columns = (
        R1Column(1, "enabled", R1ScalarType.from_postgres("bool"), nullable=False),
        R1Column(2, "count", R1ScalarType.from_postgres("int8"), nullable=False),
        R1Column(3, "amount", R1ScalarType.from_postgres("numeric(12,2)"), nullable=False),
        R1Column(4, "ratio", R1ScalarType.from_postgres("float8"), nullable=False),
        R1Column(5, "id", R1ScalarType.from_postgres("uuid"), nullable=False),
        R1Column(6, "day", R1ScalarType.from_postgres("date"), nullable=False),
        R1Column(7, "clock", R1ScalarType.from_postgres("time(6)"), nullable=False),
        R1Column(8, "created", R1ScalarType.from_postgres("timestamp(6)"), nullable=False),
        R1Column(9, "instant", R1ScalarType.from_postgres("timestamptz(6)"), nullable=False),
        R1Column(10, "note", R1ScalarType.from_postgres("varchar(12)"), nullable=True),
        R1Column(11, "payload", R1ScalarType.from_postgres("bytea"), nullable=False),
    )
    values = (
        True,
        -7,
        Decimal("-0.00"),
        -0.0,
        UUID("00112233-4455-6677-8899-aabbccddeeff"),
        date(2000, 1, 2),
        time(1, 2, 3, 4),
        datetime(1999, 12, 31, 23, 59, 59, 999999),
        datetime(2000, 1, 1, 3, 0, tzinfo=UTC),
        None,
        b"\x00\xff",
    )

    row = canonical_row_bytes(columns, values)

    assert row.startswith(b"dpone-r1-row-hash-v1\0")
    assert (
        canonical_row_hash(columns, values).hex() == "24138396830f9b5413eff15e3a6dc4ba45b4acc17325240913da6e419d0994f9"
    )


def test_key_payload_supports_only_one_non_null_integer_or_uuid() -> None:
    assert canonical_key_payload(R1ScalarType.from_postgres("int4"), -1).hex() == (
        "64706f6e652d72312d6b65792d763100030000000000000001ff"
    )
    assert (
        canonical_key_payload(
            R1ScalarType.from_postgres("uuid"),
            UUID("00112233-4455-6677-8899-aabbccddeeff"),
        ).hex()
        == "64706f6e652d72312d6b65792d76310008000000000000001000112233445566778899aabbccddeeff"
    )
    with pytest.raises(R1HashContractError, match="business key"):
        canonical_key_payload(R1ScalarType.from_postgres("text"), "x")
    with pytest.raises(R1HashContractError, match="NULL"):
        canonical_key_payload(R1ScalarType.from_postgres("int8"), None)


@pytest.mark.parametrize("value", [float("nan"), float("inf"), float("-inf")])
def test_non_finite_float_fails_closed(value: float) -> None:
    with pytest.raises(R1HashContractError, match="non-finite"):
        canonical_row_bytes(
            (R1Column(1, "value", R1ScalarType.from_postgres("float8"), nullable=False),),
            (value,),
        )


def test_bit_one_is_supported_but_temporal_rounding_is_forbidden() -> None:
    bit = R1ScalarType.from_postgres("bit(1)")
    assert canonical_row_bytes((R1Column(1, "flag", bit, False),), (1,)).endswith(b"\x01")
    with pytest.raises(R1HashContractError, match="temporal value"):
        canonical_row_bytes(
            (R1Column(1, "clock", R1ScalarType.from_postgres("time(3)"), False),),
            (time(1, 2, 3, 1),),
        )


@pytest.mark.parametrize("source_type", ["jsonb", "bpchar", "numeric", "numeric(39,0)", "timetz", "bit(2)"])
def test_unsupported_type_fails_with_stable_error(source_type: str) -> None:
    with pytest.raises(R1HashContractError, match="DPONE_POSTGRES_MSSQL_UNSUPPORTED_TYPE"):
        R1ScalarType.from_postgres(source_type)


def test_artifact_digest_is_ordered_collision_safe_and_has_empty_vector() -> None:
    schema = bytes.fromhex("33" * 32)
    key = canonical_key_payload(R1ScalarType.from_postgres("int8"), 1)
    row = canonical_row_bytes(
        (R1Column(1, "id", R1ScalarType.from_postgres("int8"), nullable=False),),
        (1,),
    )

    assert artifact_digest("batch_payload", schema, ()).hex() == (
        "6ecacc615299e9eb9b57bf2425b8b845574f493965500e25dc954006409d1af0"
    )
    first = artifact_digest("batch_payload", schema, ((key, row),))
    assert first.hex() == "cb22d0a50a954ccfc1dd1ae2a3a911c70a4039d9f9f8e9615e3aae187e6cb05c"
    assert artifact_set_digest((("batch_payload", first),)).hex() == (
        "59d2101dd96801b6a404fbc794790ddc9ae2ad7771c20075d42d7f2f8861ef7d"
    )
    with pytest.raises(R1HashContractError, match="ordered"):
        artifact_digest("batch_payload", schema, ((key + b"x", row), (key, row)))
