# ruff: noqa: F822
"""Operational maturity services for self-service dpone controls."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "ApprovalRecordService",
    "ArtifactIndexService",
    "BenchmarkBaselineService",
    "BenchmarkSloGateService",
    "CatalogPublicationService",
    "CertificationHarnessService",
    "CertificationHistoryService",
    "CertificationSuiteService",
    "ChangeRequestService",
    "ConnectionDoctorService",
    "ConnectorBadgeService",
    "ConnectorCertificationPackService",
    "ConnectorMarketplaceService",
    "DataContractEvidenceBundleWriter",
    "DataContractService",
    "DbtLineageService",
    "DeploymentProfileRenderer",
    "DeploymentRecordService",
    "DlqReplayService",
    "DlqRetentionService",
    "DlqService",
    "DocsPublishPackService",
    "EnvironmentDriftService",
    "EvidenceBundleService",
    "EvidenceChainService",
    "GoLiveGateService",
    "IndustrialReadinessService",
    "LiveCertificationAutomationService",
    "LiveStateReconciliationCertificationService",
    "LoadPackageService",
    "ManifestBundleService",
    "ObservabilityPackService",
    "OpenLineageExportService",
    "OpsServiceCatalog",
    "OpsDiffService",
    "OpsIncidentPackService",
    "OpsPolicyService",
    "OpsSecurityAuditService",
    "OpsSloService",
    "PerformanceCertificationService",
    "PostDeployVerifyService",
    "PreReleaseChecklistService",
    "ProductionMaturityService",
    "QuarantineService",
    "ReconciliationService",
    "ReleaseCloseService",
    "ReleaseEvidencePackService",
    "ReleaseGateService",
    "ReleaseOrchestratorService",
    "ReleasePromotionService",
    "RouteExecutionService",
    "RouteBootstrapService",
    "RouteConformanceLiveService",
    "RouteConformanceService",
    "RouteDataQualityService",
    "RouteDoctorService",
    "RouteLiveCertificationService",
    "RouteReleaseCandidateExecutorService",
    "RouteReleaseCandidateOrchestratorService",
    "RouteReleaseGateService",
    "RouteStatePromotionService",
    "RouteReadinessService",
    "RouteCertificationPackService",
    "CdcOpsCatalog",
    "CdcApplyCertificationService",
    "CdcObservabilityEvidenceService",
    "CdcPromotionGateService",
    "CdcRecoveryEvidenceService",
    "CdcRuntimeRunService",
    "CdcSchemaEvolutionEvidenceService",
    "SnapshotCdcHandoffService",
    "SourceDiscoveryService",
    "RollbackExecutionService",
    "RollbackPlanService",
    "RunRegistryService",
    "RunbookPackService",
    "RuntimeRecoveryPlanner",
    "StagingEvidenceService",
    "UnifiedRunEvidencePackWriter",
]

_EXPORTS: dict[str, str] = {
    "ApprovalRecordService": "dpone.ops.approval_record:ApprovalRecordService",
    "ArtifactIndexService": "dpone.ops.artifact_index:ArtifactIndexService",
    "BenchmarkBaselineService": "dpone.ops.benchmark_baseline:BenchmarkBaselineService",
    "BenchmarkSloGateService": "dpone.ops.benchmark_slo_gate:BenchmarkSloGateService",
    "CatalogPublicationService": "dpone.ops.catalog_publish:CatalogPublicationService",
    "CertificationHarnessService": "dpone.ops.certification:CertificationHarnessService",
    "CertificationHistoryService": "dpone.ops.certification_history:CertificationHistoryService",
    "CertificationSuiteService": "dpone.ops.certification_suite:CertificationSuiteService",
    "ChangeRequestService": "dpone.ops.change_request:ChangeRequestService",
    "ConnectionDoctorService": "dpone.ops.connection_doctor:ConnectionDoctorService",
    "ConnectorBadgeService": "dpone.ops.connector_badges:ConnectorBadgeService",
    "ConnectorCertificationPackService": "dpone.ops.certification_pack:ConnectorCertificationPackService",
    "ConnectorMarketplaceService": "dpone.ops.marketplace:ConnectorMarketplaceService",
    "DataContractEvidenceBundleWriter": "dpone.ops.data_contract_evidence:DataContractEvidenceBundleWriter",
    "DataContractService": "dpone.ops.contracts:DataContractService",
    "DbtLineageService": "dpone.ops.dbt_lineage:DbtLineageService",
    "DeploymentProfileRenderer": "dpone.ops.deploy_profiles:DeploymentProfileRenderer",
    "DeploymentRecordService": "dpone.ops.deployment_record:DeploymentRecordService",
    "DlqReplayService": "dpone.ops.dlq:DlqReplayService",
    "DlqRetentionService": "dpone.ops.dlq:DlqRetentionService",
    "DlqService": "dpone.ops.dlq:DlqService",
    "DocsPublishPackService": "dpone.ops.docs_publish_pack:DocsPublishPackService",
    "EnvironmentDriftService": "dpone.ops.env_drift:EnvironmentDriftService",
    "EvidenceBundleService": "dpone.ops.evidence:EvidenceBundleService",
    "EvidenceChainService": "dpone.ops.evidence_chain:EvidenceChainService",
    "GoLiveGateService": "dpone.ops.gate:GoLiveGateService",
    "IndustrialReadinessService": "dpone.ops.industrial_readiness:IndustrialReadinessService",
    "LiveCertificationAutomationService": "dpone.ops.live_certification:LiveCertificationAutomationService",
    "LiveStateReconciliationCertificationService": "dpone.ops.live_state_reconciliation:LiveStateReconciliationCertificationService",
    "LoadPackageService": "dpone.ops.packages:LoadPackageService",
    "ManifestBundleService": "dpone.ops.manifest_bundle:ManifestBundleService",
    "ObservabilityPackService": "dpone.ops.observability_pack:ObservabilityPackService",
    "OpenLineageExportService": "dpone.ops.openlineage_export:OpenLineageExportService",
    "OpsServiceCatalog": "dpone.ops.service_catalog:OpsServiceCatalog",
    "OpsDiffService": "dpone.ops.diff:OpsDiffService",
    "OpsIncidentPackService": "dpone.ops.incident:OpsIncidentPackService",
    "OpsPolicyService": "dpone.ops.policy:OpsPolicyService",
    "OpsSecurityAuditService": "dpone.ops.security:OpsSecurityAuditService",
    "OpsSloService": "dpone.ops.slo:OpsSloService",
    "PerformanceCertificationService": "dpone.ops.performance_certification:PerformanceCertificationService",
    "PostDeployVerifyService": "dpone.ops.post_deploy_verify:PostDeployVerifyService",
    "PreReleaseChecklistService": "dpone.ops.pre_release_checklist:PreReleaseChecklistService",
    "ProductionMaturityService": "dpone.ops.production_maturity:ProductionMaturityService",
    "QuarantineService": "dpone.ops.quarantine:QuarantineService",
    "ReconciliationService": "dpone.ops.reconciliation:ReconciliationService",
    "ReleaseCloseService": "dpone.ops.release_close:ReleaseCloseService",
    "ReleaseEvidencePackService": "dpone.ops.release_evidence_pack:ReleaseEvidencePackService",
    "ReleaseGateService": "dpone.ops.release_gate:ReleaseGateService",
    "ReleaseOrchestratorService": "dpone.ops.release_orchestrator:ReleaseOrchestratorService",
    "ReleasePromotionService": "dpone.ops.release_promote:ReleasePromotionService",
    "RouteExecutionService": "dpone.ops.route_execution:RouteExecutionService",
    "RouteBootstrapService": "dpone.ops.route_bootstrap:RouteBootstrapService",
    "RouteConformanceLiveService": "dpone.ops.route_conformance_live:RouteConformanceLiveService",
    "RouteConformanceService": "dpone.ops.route_conformance:RouteConformanceService",
    "RouteDataQualityService": "dpone.ops.route_data_quality:RouteDataQualityService",
    "RouteDoctorService": "dpone.ops.route_doctor:RouteDoctorService",
    "RouteLiveCertificationService": "dpone.ops.route_live_certification:RouteLiveCertificationService",
    "RouteReleaseCandidateExecutorService": "dpone.ops.route_rc_executor:RouteReleaseCandidateExecutorService",
    "RouteReleaseCandidateOrchestratorService": "dpone.ops.route_rc_orchestrator:RouteReleaseCandidateOrchestratorService",
    "RouteReleaseGateService": "dpone.ops.route_release_gate:RouteReleaseGateService",
    "RouteStatePromotionService": "dpone.ops.route_state_promotion:RouteStatePromotionService",
    "RouteReadinessService": "dpone.ops.route_readiness:RouteReadinessService",
    "RouteCertificationPackService": "dpone.ops.routes.certification:RouteCertificationPackService",
    "CdcOpsCatalog": "dpone.ops.catalog_cdc:CdcOpsCatalog",
    "CdcApplyCertificationService": "dpone.ops.cdc.apply:CdcApplyCertificationService",
    "CdcObservabilityEvidenceService": "dpone.ops.cdc.observability:CdcObservabilityEvidenceService",
    "CdcPromotionGateService": "dpone.ops.cdc.promotion:CdcPromotionGateService",
    "CdcRecoveryEvidenceService": "dpone.ops.cdc.recovery:CdcRecoveryEvidenceService",
    "CdcRuntimeRunService": "dpone.ops.cdc.runtime_run:CdcRuntimeRunService",
    "CdcSchemaEvolutionEvidenceService": "dpone.ops.cdc.schema_evolution:CdcSchemaEvolutionEvidenceService",
    "SnapshotCdcHandoffService": "dpone.ops.cdc.handoff:SnapshotCdcHandoffService",
    "SourceDiscoveryService": "dpone.ops.source_discovery:SourceDiscoveryService",
    "RollbackExecutionService": "dpone.ops.rollback_execute:RollbackExecutionService",
    "RollbackPlanService": "dpone.ops.rollback:RollbackPlanService",
    "RunRegistryService": "dpone.ops.run_registry:RunRegistryService",
    "RunbookPackService": "dpone.ops.runbook_pack:RunbookPackService",
    "RuntimeRecoveryPlanner": "dpone.ops.recovery:RuntimeRecoveryPlanner",
    "StagingEvidenceService": "dpone.ops.staging_evidence:StagingEvidenceService",
    "UnifiedRunEvidencePackWriter": "dpone.ops.evidence_pack:UnifiedRunEvidencePackWriter",
}


def __getattr__(name: str) -> Any:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr = target.split(":")
    value = getattr(import_module(module_name), attr)
    globals()[name] = value
    return value
