"""Reusable source -> sink route readiness taxonomy."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "RouteEvidenceItem",
    "RouteEvidenceProbe",
    "RouteEvidenceProbeResult",
    "RouteEvidenceReader",
    "RouteExecutionLedgerReport",
    "RouteExecutionLedgerStore",
    "RouteExecutionLedgerStoreFactory",
    "RouteExecutionLease",
    "RouteExecutionStage",
    "RouteExecutionStatus",
    "RouteExecutionStep",
    "LocalRouteExecutionLedgerStore",
    "ArtifactSummary",
    "ConnectionDoctorReport",
    "DiscoveredColumn",
    "DiscoveredTable",
    "OnboardingCheck",
    "OnboardingStatus",
    "SqliteRouteExecutionLedgerStore",
    "RouteCertificationPackReport",
    "RouteCertificationPackService",
    "RouteCertificationBundleReport",
    "RouteCertificationReleaseDecision",
    "RouteCertificationReleaseItem",
    "RouteCertificationReleaseFinalizerCheck",
    "RouteCertificationReleaseFinalizerDecision",
    "RouteCertificationReleaseFinalizerPolicy",
    "RouteCertificationReleaseFinalizerReport",
    "RouteCertificationReleaseHistoryEntry",
    "RouteCertificationReleasePolicy",
    "RouteCertificationReleaseReport",
    "RouteCertificationDecision",
    "RouteCertificationPolicy",
    "RouteCertificationStage",
    "RouteBootstrapReport",
    "RouteConformanceAggregateReport",
    "RouteConformanceArtifactSummary",
    "RouteConformanceChunk",
    "RouteConformanceColumn",
    "RouteConformanceDataset",
    "RouteConformanceDatasetProfile",
    "RouteConformanceDecision",
    "RouteConformanceLiveConfig",
    "RouteConformanceLiveReport",
    "RouteConformanceLiveStep",
    "RouteConformanceLiveAdapter",
    "RouteConformanceLiveStore",
    "RouteConformanceRouteExecutor",
    "RouteConformanceSchemaEvolutionApplier",
    "RouteConformanceSnapshotReader",
    "RouteConformanceSourceSeeder",
    "MemoryRouteConformanceLiveStore",
    "VendorLiveRouteBinding",
    "VendorRouteConformanceLiveAdapter",
    "RouteConformanceReport",
    "RouteConformanceSnapshot",
    "RouteConformanceVerificationResult",
    "RouteDataQualityDecision",
    "RouteDataQualityDimension",
    "RouteDataQualityEvidence",
    "RouteDataQualityEvidenceReader",
    "RouteDataQualityExceptionSummary",
    "RouteDataQualityPolicy",
    "RouteDataQualityReport",
    "RouteDataQualityService",
    "RouteDataQualityStatus",
    "RouteDataQualityThresholds",
    "RouteDoctorReport",
    "RouteKey",
    "RouteLiveCertificationDecision",
    "RouteLiveCertificationEvidence",
    "RouteLiveCertificationPolicy",
    "RouteLiveCertificationReport",
    "RouteLiveCertificationStep",
    "RouteProfile",
    "RouteProfileCatalog",
    "RouteRefreshApproval",
    "RouteRefreshChunk",
    "RouteRefreshChunkExecutionRequest",
    "RouteRefreshChunkExecutionResult",
    "RouteRefreshDecision",
    "RouteRefreshEvidence",
    "RouteRefreshEvidenceReader",
    "RouteRefreshExecutionArtifact",
    "RouteRefreshExecutionDecision",
    "RouteRefreshExecutionPolicy",
    "RouteRefreshExecutionReport",
    "RouteRefreshExecutionService",
    "RouteRefreshExecutionStatus",
    "RouteRefreshExecutor",
    "RouteRefreshExecutorRegistry",
    "RouteRefreshPlanPolicy",
    "RouteRefreshPlanReport",
    "RouteRefreshPlanService",
    "RouteRefreshReason",
    "RouteRefreshStateRewind",
    "RouteRefreshStatus",
    "RouteRefreshWindow",
    "RouteRefreshWindowKind",
    "DryRunRouteRefreshExecutor",
    "MssqlClickHouseRefreshConfig",
    "MssqlClickHouseRouteRefreshExecutor",
    "CommandProcessResult",
    "CommandProcessRunner",
    "DEFAULT_ROUTE_DATA_QUALITY_EVIDENCE",
    "RouteRcExecutionArtifact",
    "RouteRcExecutionDecision",
    "RouteRcExecutionPolicy",
    "RouteRcExecutionReport",
    "RouteRcExecutionStep",
    "RouteRcOrchestrationDecision",
    "RouteRcOrchestrationPolicy",
    "RouteRcOrchestrationReport",
    "RouteRcOrchestrationStep",
    "RouteReadinessDecision",
    "RouteReadinessPolicy",
    "RouteReadinessReport",
    "RouteReconciliationRepairReport",
    "RouteReconciliationRepairService",
    "RouteRepairAction",
    "RouteRepairPlan",
    "RouteReleaseGateDecision",
    "RouteReleaseGateEvidence",
    "RouteReleaseGatePolicy",
    "RouteReleaseGateReport",
    "RouteRunDecision",
    "RouteRunContractStage",
    "RouteRunEvidence",
    "RouteRunEvidenceBundle",
    "RouteRunExecutionContract",
    "RouteRunExecutionContractBuilder",
    "RouteRunIdentity",
    "RouteRunMode",
    "RouteRunPhase",
    "RouteRunSupervisorPolicy",
    "RouteRunSupervisorService",
    "RouteRunStatus",
    "RouteSchemaApplyDecision",
    "RouteSchemaEvolutionReport",
    "RouteSchemaEvolutionService",
    "RouteCommitReceipt",
    "RouteStatePromotionReport",
    "RouteStatePromotionDecision",
    "RouteStateRecord",
    "RouteStateStore",
    "RouteStateStoreFactory",
    "SourceDiscoveryReport",
    "LocalRouteStateStore",
    "SqliteRouteStateStore",
]

_EXPORTS: dict[str, str] = {
    "RouteEvidenceItem": "dpone.ops.routes.models:RouteEvidenceItem",
    "RouteEvidenceProbe": "dpone.ops.routes.certification:RouteEvidenceProbe",
    "RouteEvidenceProbeResult": "dpone.ops.routes.certification:RouteEvidenceProbeResult",
    "RouteEvidenceReader": "dpone.ops.routes.evidence:RouteEvidenceReader",
    "RouteExecutionLedgerReport": "dpone.ops.routes.execution_models:RouteExecutionLedgerReport",
    "RouteExecutionLedgerStore": "dpone.ops.routes.execution_store:RouteExecutionLedgerStore",
    "RouteExecutionLedgerStoreFactory": "dpone.ops.routes.execution_store_factory:RouteExecutionLedgerStoreFactory",
    "RouteExecutionLease": "dpone.ops.routes.execution_models:RouteExecutionLease",
    "RouteExecutionStage": "dpone.ops.routes.execution_models:RouteExecutionStage",
    "RouteExecutionStatus": "dpone.ops.routes.execution_models:RouteExecutionStatus",
    "RouteExecutionStep": "dpone.ops.routes.execution_models:RouteExecutionStep",
    "LocalRouteExecutionLedgerStore": "dpone.ops.routes.execution_store:LocalRouteExecutionLedgerStore",
    "ArtifactSummary": "dpone.ops.routes.bootstrap_models:ArtifactSummary",
    "ConnectionDoctorReport": "dpone.ops.routes.bootstrap_models:ConnectionDoctorReport",
    "DiscoveredColumn": "dpone.ops.routes.bootstrap_models:DiscoveredColumn",
    "DiscoveredTable": "dpone.ops.routes.bootstrap_models:DiscoveredTable",
    "OnboardingCheck": "dpone.ops.routes.bootstrap_models:OnboardingCheck",
    "OnboardingStatus": "dpone.ops.routes.bootstrap_models:OnboardingStatus",
    "SqliteRouteExecutionLedgerStore": "dpone.ops.routes.execution_store_sqlite:SqliteRouteExecutionLedgerStore",
    "RouteCertificationPackReport": "dpone.ops.routes.certification:RouteCertificationPackReport",
    "RouteCertificationPackService": "dpone.ops.routes.certification:RouteCertificationPackService",
    "RouteCertificationBundleReport": "dpone.ops.routes.certify_models:RouteCertificationBundleReport",
    "RouteCertificationReleaseDecision": "dpone.ops.routes.certify_release_policy:RouteCertificationReleaseDecision",
    "RouteCertificationReleaseItem": "dpone.ops.routes.certify_release_models:RouteCertificationReleaseItem",
    "RouteCertificationReleaseFinalizerCheck": "dpone.ops.routes.certify_release_finalizer_models:RouteCertificationReleaseFinalizerCheck",
    "RouteCertificationReleaseFinalizerDecision": "dpone.ops.routes.certify_release_finalizer_policy:RouteCertificationReleaseFinalizerDecision",
    "RouteCertificationReleaseFinalizerPolicy": "dpone.ops.routes.certify_release_finalizer_policy:RouteCertificationReleaseFinalizerPolicy",
    "RouteCertificationReleaseFinalizerReport": "dpone.ops.routes.certify_release_finalizer_models:RouteCertificationReleaseFinalizerReport",
    "RouteCertificationReleaseHistoryEntry": "dpone.ops.routes.certify_release_finalizer_models:RouteCertificationReleaseHistoryEntry",
    "RouteCertificationReleasePolicy": "dpone.ops.routes.certify_release_policy:RouteCertificationReleasePolicy",
    "RouteCertificationReleaseReport": "dpone.ops.routes.certify_release_models:RouteCertificationReleaseReport",
    "RouteCertificationDecision": "dpone.ops.routes.certify_policy:RouteCertificationDecision",
    "RouteCertificationPolicy": "dpone.ops.routes.certify_policy:RouteCertificationPolicy",
    "RouteCertificationStage": "dpone.ops.routes.certify_models:RouteCertificationStage",
    "RouteBootstrapReport": "dpone.ops.routes.bootstrap_models:RouteBootstrapReport",
    "RouteConformanceAggregateReport": "dpone.ops.routes.conformance_models:RouteConformanceAggregateReport",
    "RouteConformanceArtifactSummary": "dpone.ops.routes.conformance_models:RouteConformanceArtifactSummary",
    "RouteConformanceChunk": "dpone.ops.routes.conformance_models:RouteConformanceChunk",
    "RouteConformanceColumn": "dpone.ops.routes.conformance_models:RouteConformanceColumn",
    "RouteConformanceDataset": "dpone.ops.routes.conformance_models:RouteConformanceDataset",
    "RouteConformanceDatasetProfile": "dpone.ops.routes.conformance_models:RouteConformanceDatasetProfile",
    "RouteConformanceDecision": "dpone.ops.routes.conformance_models:RouteConformanceDecision",
    "RouteConformanceLiveConfig": "dpone.ops.routes.conformance_live_models:RouteConformanceLiveConfig",
    "RouteConformanceLiveReport": "dpone.ops.routes.conformance_live_models:RouteConformanceLiveReport",
    "RouteConformanceLiveStep": "dpone.ops.routes.conformance_live_models:RouteConformanceLiveStep",
    "RouteConformanceLiveAdapter": "dpone.ops.routes.conformance_live_ports:RouteConformanceLiveAdapter",
    "RouteConformanceLiveStore": "dpone.ops.routes.conformance_vendor_live:RouteConformanceLiveStore",
    "RouteConformanceRouteExecutor": "dpone.ops.routes.conformance_live_ports:RouteConformanceRouteExecutor",
    "RouteConformanceSchemaEvolutionApplier": "dpone.ops.routes.conformance_live_ports:RouteConformanceSchemaEvolutionApplier",
    "RouteConformanceSnapshotReader": "dpone.ops.routes.conformance_live_ports:RouteConformanceSnapshotReader",
    "RouteConformanceSourceSeeder": "dpone.ops.routes.conformance_live_ports:RouteConformanceSourceSeeder",
    "MemoryRouteConformanceLiveStore": "dpone.ops.routes.conformance_vendor_live:MemoryRouteConformanceLiveStore",
    "VendorLiveRouteBinding": "dpone.ops.routes.conformance_vendor_live:VendorLiveRouteBinding",
    "VendorRouteConformanceLiveAdapter": "dpone.ops.routes.conformance_vendor_live:VendorRouteConformanceLiveAdapter",
    "RouteConformanceReport": "dpone.ops.routes.conformance_models:RouteConformanceReport",
    "RouteConformanceSnapshot": "dpone.ops.routes.conformance_models:RouteConformanceSnapshot",
    "RouteConformanceVerificationResult": "dpone.ops.routes.conformance_models:RouteConformanceVerificationResult",
    "RouteDataQualityDecision": "dpone.ops.routes.data_quality_policy:RouteDataQualityDecision",
    "RouteDataQualityDimension": "dpone.ops.routes.data_quality_models:RouteDataQualityDimension",
    "RouteDataQualityEvidence": "dpone.ops.routes.data_quality_models:RouteDataQualityEvidence",
    "RouteDataQualityEvidenceReader": "dpone.ops.routes.data_quality_evidence:RouteDataQualityEvidenceReader",
    "RouteDataQualityExceptionSummary": "dpone.ops.routes.data_quality_models:RouteDataQualityExceptionSummary",
    "RouteDataQualityPolicy": "dpone.ops.routes.data_quality_policy:RouteDataQualityPolicy",
    "RouteDataQualityReport": "dpone.ops.routes.data_quality_models:RouteDataQualityReport",
    "RouteDataQualityService": "dpone.ops.route_data_quality:RouteDataQualityService",
    "RouteDataQualityStatus": "dpone.ops.routes.data_quality_models:RouteDataQualityStatus",
    "RouteDataQualityThresholds": "dpone.ops.routes.data_quality_models:RouteDataQualityThresholds",
    "RouteDoctorReport": "dpone.ops.routes.bootstrap_models:RouteDoctorReport",
    "RouteKey": "dpone.ops.routes.models:RouteKey",
    "RouteLiveCertificationDecision": "dpone.ops.routes.live_certification_policy:RouteLiveCertificationDecision",
    "RouteLiveCertificationEvidence": "dpone.ops.routes.live_certification_models:RouteLiveCertificationEvidence",
    "RouteLiveCertificationPolicy": "dpone.ops.routes.live_certification_policy:RouteLiveCertificationPolicy",
    "RouteLiveCertificationReport": "dpone.ops.routes.live_certification_models:RouteLiveCertificationReport",
    "RouteLiveCertificationStep": "dpone.ops.routes.live_certification_models:RouteLiveCertificationStep",
    "RouteProfile": "dpone.ops.routes.models:RouteProfile",
    "RouteProfileCatalog": "dpone.ops.routes.catalog:RouteProfileCatalog",
    "RouteRefreshApproval": "dpone.ops.routes.refresh_plan_models:RouteRefreshApproval",
    "RouteRefreshChunk": "dpone.ops.routes.refresh_plan_models:RouteRefreshChunk",
    "RouteRefreshChunkExecutionRequest": "dpone.ops.routes.refresh_execution_models:RouteRefreshChunkExecutionRequest",
    "RouteRefreshChunkExecutionResult": "dpone.ops.routes.refresh_execution_models:RouteRefreshChunkExecutionResult",
    "RouteRefreshDecision": "dpone.ops.routes.refresh_plan_policy:RouteRefreshDecision",
    "RouteRefreshEvidence": "dpone.ops.routes.refresh_plan_models:RouteRefreshEvidence",
    "RouteRefreshEvidenceReader": "dpone.ops.routes.refresh_plan_evidence:RouteRefreshEvidenceReader",
    "RouteRefreshExecutionArtifact": "dpone.ops.routes.refresh_execution_models:RouteRefreshExecutionArtifact",
    "RouteRefreshExecutionDecision": "dpone.ops.routes.refresh_execution_policy:RouteRefreshExecutionDecision",
    "RouteRefreshExecutionPolicy": "dpone.ops.routes.refresh_execution_policy:RouteRefreshExecutionPolicy",
    "RouteRefreshExecutionReport": "dpone.ops.routes.refresh_execution_models:RouteRefreshExecutionReport",
    "RouteRefreshExecutionService": "dpone.ops.route_refresh_execute:RouteRefreshExecutionService",
    "RouteRefreshExecutionStatus": "dpone.ops.routes.refresh_execution_models:RouteRefreshExecutionStatus",
    "RouteRefreshExecutor": "dpone.ops.routes.refresh_execution_executor:RouteRefreshExecutor",
    "RouteRefreshExecutorRegistry": "dpone.ops.routes.refresh_executors:RouteRefreshExecutorRegistry",
    "RouteRefreshPlanPolicy": "dpone.ops.routes.refresh_plan_policy:RouteRefreshPlanPolicy",
    "RouteRefreshPlanReport": "dpone.ops.routes.refresh_plan_models:RouteRefreshPlanReport",
    "RouteRefreshPlanService": "dpone.ops.route_refresh_plan:RouteRefreshPlanService",
    "RouteRefreshReason": "dpone.ops.routes.refresh_plan_models:RouteRefreshReason",
    "RouteRefreshStateRewind": "dpone.ops.routes.refresh_plan_models:RouteRefreshStateRewind",
    "RouteRefreshStatus": "dpone.ops.routes.refresh_plan_models:RouteRefreshStatus",
    "RouteRefreshWindow": "dpone.ops.routes.refresh_plan_models:RouteRefreshWindow",
    "RouteRefreshWindowKind": "dpone.ops.routes.refresh_plan_models:RouteRefreshWindowKind",
    "DryRunRouteRefreshExecutor": "dpone.ops.routes.refresh_execution_executor:DryRunRouteRefreshExecutor",
    "MssqlClickHouseRefreshConfig": "dpone.ops.routes.refresh_executors:MssqlClickHouseRefreshConfig",
    "MssqlClickHouseRouteRefreshExecutor": "dpone.ops.routes.refresh_executors:MssqlClickHouseRouteRefreshExecutor",
    "CommandProcessResult": "dpone.ops.routes.rc_executor_runner:CommandProcessResult",
    "CommandProcessRunner": "dpone.ops.routes.rc_executor_runner:CommandProcessRunner",
    "DEFAULT_ROUTE_DATA_QUALITY_EVIDENCE": "dpone.ops.routes.data_quality_evidence:DEFAULT_ROUTE_DATA_QUALITY_EVIDENCE",
    "RouteRcExecutionArtifact": "dpone.ops.routes.rc_executor_models:RouteRcExecutionArtifact",
    "RouteRcExecutionDecision": "dpone.ops.routes.rc_executor_models:RouteRcExecutionDecision",
    "RouteRcExecutionPolicy": "dpone.ops.routes.rc_executor_policy:RouteRcExecutionPolicy",
    "RouteRcExecutionReport": "dpone.ops.routes.rc_executor_models:RouteRcExecutionReport",
    "RouteRcExecutionStep": "dpone.ops.routes.rc_executor_models:RouteRcExecutionStep",
    "RouteRcOrchestrationDecision": "dpone.ops.routes.rc_orchestrator_models:RouteRcOrchestrationDecision",
    "RouteRcOrchestrationPolicy": "dpone.ops.routes.rc_orchestrator_policy:RouteRcOrchestrationPolicy",
    "RouteRcOrchestrationReport": "dpone.ops.routes.rc_orchestrator_models:RouteRcOrchestrationReport",
    "RouteRcOrchestrationStep": "dpone.ops.routes.rc_orchestrator_models:RouteRcOrchestrationStep",
    "RouteReadinessDecision": "dpone.ops.routes.models:RouteReadinessDecision",
    "RouteReadinessPolicy": "dpone.ops.routes.policy:RouteReadinessPolicy",
    "RouteReadinessReport": "dpone.ops.routes.models:RouteReadinessReport",
    "RouteReconciliationRepairReport": "dpone.ops.routes.models:RouteReconciliationRepairReport",
    "RouteReconciliationRepairService": "dpone.ops.routes.reconciliation_repair:RouteReconciliationRepairService",
    "RouteRepairAction": "dpone.ops.routes.models:RouteRepairAction",
    "RouteRepairPlan": "dpone.ops.routes.models:RouteRepairPlan",
    "RouteReleaseGateDecision": "dpone.ops.routes.release_gate_policy:RouteReleaseGateDecision",
    "RouteReleaseGateEvidence": "dpone.ops.routes.release_gate_models:RouteReleaseGateEvidence",
    "RouteReleaseGatePolicy": "dpone.ops.routes.release_gate_policy:RouteReleaseGatePolicy",
    "RouteReleaseGateReport": "dpone.ops.routes.release_gate_models:RouteReleaseGateReport",
    "RouteRunDecision": "dpone.ops.routes.run_supervisor_models:RouteRunDecision",
    "RouteRunContractStage": "dpone.ops.routes.run_supervisor_models:RouteRunContractStage",
    "RouteRunEvidence": "dpone.ops.routes.run_supervisor_models:RouteRunEvidence",
    "RouteRunEvidenceBundle": "dpone.ops.routes.run_supervisor_models:RouteRunEvidenceBundle",
    "RouteRunExecutionContract": "dpone.ops.routes.run_supervisor_models:RouteRunExecutionContract",
    "RouteRunExecutionContractBuilder": "dpone.ops.routes.run_supervisor_contract:RouteRunExecutionContractBuilder",
    "RouteRunIdentity": "dpone.ops.routes.run_supervisor_models:RouteRunIdentity",
    "RouteRunMode": "dpone.ops.routes.run_supervisor_models:RouteRunMode",
    "RouteRunPhase": "dpone.ops.routes.run_supervisor_models:RouteRunPhase",
    "RouteRunSupervisorPolicy": "dpone.ops.routes.run_supervisor_policy:RouteRunSupervisorPolicy",
    "RouteRunSupervisorService": "dpone.ops.routes.run_supervisor:RouteRunSupervisorService",
    "RouteRunStatus": "dpone.ops.routes.run_supervisor_models:RouteRunStatus",
    "RouteSchemaApplyDecision": "dpone.ops.routes.models:RouteSchemaApplyDecision",
    "RouteSchemaEvolutionReport": "dpone.ops.routes.models:RouteSchemaEvolutionReport",
    "RouteSchemaEvolutionService": "dpone.ops.routes.schema_evolution:RouteSchemaEvolutionService",
    "RouteCommitReceipt": "dpone.ops.routes.state_promotion_models:RouteCommitReceipt",
    "RouteStatePromotionReport": "dpone.ops.routes.state_promotion_models:RouteStatePromotionReport",
    "RouteStatePromotionDecision": "dpone.ops.routes.state_promotion_policy:RouteStatePromotionDecision",
    "RouteStateRecord": "dpone.ops.routes.state_promotion_models:RouteStateRecord",
    "RouteStateStore": "dpone.ops.routes.state_store:RouteStateStore",
    "RouteStateStoreFactory": "dpone.ops.routes.state_store_factory:RouteStateStoreFactory",
    "SourceDiscoveryReport": "dpone.ops.routes.bootstrap_models:SourceDiscoveryReport",
    "LocalRouteStateStore": "dpone.ops.routes.state_store:LocalRouteStateStore",
    "SqliteRouteStateStore": "dpone.ops.routes.state_store_sqlite:SqliteRouteStateStore",
}


def __getattr__(name: str) -> Any:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr = target.split(":")
    value = getattr(import_module(module_name), attr)
    globals()[name] = value
    return value
