"""Built-in declarative templates for Phase 1A Airflow self-service."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from dpone.contracts.credential_env import connection_env_name
from dpone.readiness.airflow_preview_dag_spec import build_preview_dag_spec

PREVIEW_ENV = "local-preview"
PREVIEW_START_DATE = "2026-01-01"
_KNOWN_LEGACY_AIRFLOW_LOADER_FINGERPRINTS = frozenset(
    {
        # Generated by dpone v0.73.1 before fatal deployment-index reports
        # became import errors. Exact bytes only: user edits must conflict.
        "sha256:a0fb2abd41d89f37820be987a0ec37cff780dc570d7983afd7078b260487f3fb",
        # Generated through v0.73.31 with the cache nested under the DAG
        # checkout. The v0.73.32 topology moves cache ownership outside the
        # repository mount. Exact bytes only: user edits must conflict.
        "sha256:0e2ac81fc147865fdcaab73de97877992680cfe08342304ba0089732d42a99ee",
        # Generated by v0.73.32 development builds after moving the cache
        # outside the DAG checkout but before the canonical loader emitted
        # an exact deployment acknowledgement to a separate writable volume.
        "sha256:a4a285e42d66d6dae43b39ee90c7ffe91ae03f130d68cea2456f6e6dfb4b79e0",
    }
)

RECIPE_DEFAULTS: dict[str, dict[str, Any]] = {
    "mssql-to-clickhouse-full-refresh": {
        "domain": "sales",
        "source_type": "mssql",
        "sink_type": "clickhouse",
        "strategy": "full_refresh",
        "source_connection_ref": "mssql_dev",
        "sink_connection_ref": "clickhouse_dev",
        "source_schema": "dbo",
        "source_table": "orders",
        "target_schema": "analytics",
        "target_table": "orders",
        "unique_key": None,
    },
    "mssql-to-clickhouse-incremental": {
        "domain": "sales",
        "source_type": "mssql",
        "sink_type": "clickhouse",
        "strategy": "incremental_merge",
        "source_connection_ref": "mssql_dev",
        "sink_connection_ref": "clickhouse_dev",
        "source_schema": "dbo",
        "source_table": "orders",
        "target_schema": "analytics",
        "target_table": "orders",
        "unique_key": "id",
    },
    "postgres-to-clickhouse-incremental": {
        "domain": "sales",
        "source_type": "postgres",
        "sink_type": "clickhouse",
        "strategy": "incremental_merge",
        "source_connection_ref": "postgres_dev",
        "sink_connection_ref": "clickhouse_dev",
        "source_schema": "public",
        "source_table": "orders",
        "target_schema": "analytics",
        "target_table": "orders",
        "unique_key": "id",
    },
    "postgres-to-clickhouse-full-refresh": {
        "domain": "sales",
        "source_type": "postgres",
        "sink_type": "clickhouse",
        "strategy": "full_refresh",
        "source_connection_ref": "postgres_dev",
        "sink_connection_ref": "clickhouse_dev",
        "source_schema": "public",
        "source_table": "orders",
        "target_schema": "analytics",
        "target_table": "orders",
        "unique_key": None,
    },
}


def pipeline_payload(
    pipeline_id: str,
    recipe: str,
    defaults: dict[str, Any],
    *,
    authoring_mode: str = "flow",
    source_path: str | None = None,
    airflow: bool = True,
) -> dict[str, Any]:
    process = pipeline_process_payload(pipeline_id, defaults)
    authoring_source = source_path or f"pipelines/{pipeline_id}/pipeline.yaml"
    common = {
        "authoring": {"mode": authoring_mode, "source": authoring_source},
        "metadata": {
            "id": pipeline_id,
            "recipe": recipe,
            "domain": defaults["domain"],
            "tags": ["dpone", *(["airflow"] if airflow else [])],
            "airflow": airflow,
        },
    }
    if authoring_mode == "flow":
        return {"kind": "dpone.flow.v1", **common, "processes": [process]}
    if authoring_mode == "folder":
        return {"kind": "dpone.flow.v1", **common, "fragments": ["steps/load.yaml"]}
    if authoring_mode != "classic":
        raise ValueError(f"Unsupported authoring mode: {authoring_mode}")
    return {
        "kind": "dpone.batch.v1",
        **common,
        "defaults": {},
        "schemas": {
            defaults["source_schema"]: {
                "tables": [
                    {
                        "table": defaults["source_table"],
                        "id": pipeline_id,
                        "overrides": process,
                    }
                ]
            }
        },
    }


def pipeline_process_payload(pipeline_id: str, defaults: dict[str, Any]) -> dict[str, Any]:
    """Return the recipe process shared by flow, folder, and classic scaffolds."""

    strategy = {"mode": defaults["strategy"]}
    if defaults.get("unique_key"):
        strategy["unique_key"] = defaults["unique_key"]
    return {
        "name": pipeline_id,
        "source": {
            "type": defaults["source_type"],
            "connection_ref": defaults["source_connection_ref"],
            "table": {"schema": defaults["source_schema"], "name": defaults["source_table"]},
        },
        "sink": {
            "type": defaults["sink_type"],
            "connection_ref": defaults["sink_connection_ref"],
            "table": {"schema": defaults["target_schema"], "name": defaults["target_table"]},
            "strategy": strategy,
        },
    }


def folder_fragment_payload(pipeline_id: str, defaults: dict[str, Any]) -> dict[str, Any]:
    """Return the sole built-in folder fragment without duplicating recipe policy."""

    return {
        "kind": "dpone.flow-fragment.v1",
        "processes": [pipeline_process_payload(pipeline_id, defaults)],
    }


def domain_payload(pipeline_id: str, defaults: dict[str, Any], *, airflow: bool) -> dict[str, Any]:
    payload: dict[str, Any] = {
        "schema": "dpone.domain-catalog.v1",
        "domain": defaults["domain"],
        "workloads": {
            pipeline_id: {
                "authoring_source": f"pipelines/{pipeline_id}/pipeline.yaml",
                "connection_refs": [defaults["source_connection_ref"], defaults["sink_connection_ref"]],
                "tags": ["airflow"] if airflow else [],
            }
        },
    }
    if airflow:
        payload["dags"] = {
            pipeline_id: {
                "workloads": [pipeline_id],
                "schedule": None,
                "start_date": PREVIEW_START_DATE,
                "catchup": False,
            }
        }
    return payload


def test_payload(
    pipeline_id: str,
    pipeline_path: Path,
    *,
    process_name: str,
    pipeline_reference: str | None = None,
    fixture_reference: str | None = None,
) -> dict[str, Any]:
    return {
        "kind": "dpone.test.v1",
        "name": f"{pipeline_id}_happy_path",
        "pipeline": pipeline_reference or f"../{pipeline_path.as_posix()}",
        "process": process_name,
        "input": {
            "fixture": fixture_reference or f"fixtures/{pipeline_id}.input.jsonl",
            "format": "jsonl",
        },
        "expect": {"rows": 2, "rejected_rows": 0},
    }


def test_fixture_text(*, unique_key: tuple[str, ...]) -> str:
    """Return two deterministic synthetic rows compatible with a merge key."""

    keys = unique_key or ("id",)
    rows: list[dict[str, Any]] = []
    for row_number in (1, 2):
        row: dict[str, Any] = {key: row_number for key in keys}
        if "dpone_test_status" not in row:
            row["dpone_test_status"] = "ready"
        rows.append(row)
    return "".join(json.dumps(row, ensure_ascii=True, sort_keys=True) + "\n" for row in rows)


def dag_spec_payload(
    pipeline_id: str,
    source: dict[str, Any],
    *,
    pack: dict[str, Any],
) -> dict[str, Any]:
    domain = str(source.get("metadata", {}).get("domain") or "default")
    return build_preview_dag_spec(
        pipeline_id=pipeline_id,
        domain=domain,
        pack=pack,
        start_date=PREVIEW_START_DATE,
    )


def airflow_loader_template() -> str:
    return (
        "from airflow.providers.dpone import load_and_acknowledge_dpone_dags\n\n"
        "try:\n"
        "    from platform_semantic_refresh_runtime import application as semantic_refresh_application\n"
        "except ModuleNotFoundError as exc:\n"
        "    if exc.name != 'platform_semantic_refresh_runtime':\n"
        "        raise\n"
        "    semantic_refresh_application = None\n\n"
        "if semantic_refresh_application is None:\n"
        "    loaded = load_and_acknowledge_dpone_dags(\n"
        "        globals(),\n"
        "        index_path='/opt/airflow/.dpone-cache/current/airflow-index.json',\n"
        "        ack_path='/opt/airflow/.dpone-ack/loader-ack.json',\n"
        "        ack_root='/opt/airflow/.dpone-ack',\n"
        "    )\n"
        "else:\n"
        "    loaded = semantic_refresh_application.load_dags(\n"
        "        globals(),\n"
        "        index_path='/opt/airflow/.dpone-cache/current/airflow-index.json',\n"
        "        ack_path='/opt/airflow/.dpone-ack/loader-ack.json',\n"
        "        ack_root='/opt/airflow/.dpone-ack',\n"
        "    )\n"
        "if loaded.report.fatal:\n"
        "    error_code = (\n"
        "        loaded.report.errors[0].get('code', 'DPONE_AIRFLOW_INDEX_INVALID')\n"
        "        if loaded.report.errors\n"
        "        else 'DPONE_AIRFLOW_INDEX_INVALID'\n"
        "    )\n"
        "    raise RuntimeError(f'{error_code}: dpone Airflow deployment index could not be loaded')\n"
    )


def known_legacy_airflow_loader_fingerprint(content: bytes) -> str | None:
    """Return the exact fingerprint of a generated loader eligible for upgrade."""

    fingerprint = "sha256:" + hashlib.sha256(content).hexdigest()
    if fingerprint in _KNOWN_LEGACY_AIRFLOW_LOADER_FINGERPRINTS:
        return fingerprint
    return None


def binding_set_payload(environment: str = "dev") -> dict[str, Any]:
    return {
        "schema": "dpone.binding-set.v1",
        "environment": environment,
        "bindings": {
            "mssql_dev": {"connection_ref": "mssql_dev"},
            "clickhouse_dev": {"connection_ref": "clickhouse_dev"},
            "postgres_dev": {"connection_ref": "postgres_dev"},
        },
        "runtime": {
            "kubernetes_namespace": "airflow-dev",
            "service_account": "dpone-runtime",
            "pool": "dpone_dev",
            "resource_profile": "small",
        },
        "connection_registry_ref": f"platform/connection-registries/{environment}.yaml",
    }


def connection_registry_payload(environment: str = "dev") -> dict[str, Any]:
    return {
        "schema": "dpone.connection-registry.v1",
        "environment": environment,
        "connections": {
            "mssql_dev": _env_connection(
                "mssql",
                host="mssql-dev.local",
                port=1433,
                database="dwh",
                username_env=connection_env_name("mssql_dev", "username"),
                password_env=connection_env_name("mssql_dev", "password"),
            ),
            "clickhouse_dev": _env_connection(
                "clickhouse",
                host="clickhouse-dev.local",
                port=9000,
                database="analytics",
                username_env=connection_env_name("clickhouse_dev", "username"),
                password_env=connection_env_name("clickhouse_dev", "password"),
            ),
            "postgres_dev": _env_connection(
                "postgres",
                host="postgres-dev.local",
                port=5432,
                database="dwh",
                username_env=connection_env_name("postgres_dev", "username"),
                password_env=connection_env_name("postgres_dev", "password"),
            ),
        },
    }


def credential_runtime_payload(environment: str = "dev") -> dict[str, Any]:
    return {
        "schema": "dpone.credential-runtime.v1",
        "environment": environment,
        "runtime": {"mode": "local_development"},
        "vault": {
            "address": "https://vault.example.internal",
            "namespace": "data-platform",
            "auth": {"method": "kubernetes", "role": f"dpone-runtime-{environment}"},
        },
    }


def _env_connection(
    connection_type: str,
    *,
    host: str,
    port: int,
    database: str,
    username_env: str,
    password_env: str,
) -> dict[str, Any]:
    connection: dict[str, Any] = {"host": host, "port": port, "database": database}
    if connection_type == "mssql":
        # Deployment-owned Asset URI authority (AIP-60); host kept for credential tooling.
        connection["asset_authority"] = {"host": host, "port": port}
    return {
        "type": connection_type,
        "connection": connection,
        "credentials": {
            "resolver": "env_var",
            "support": "development_only",
            "fields": {"username": username_env, "password": password_env},
        },
    }


def _json_bytes(payload: dict[str, Any]) -> bytes:
    return (json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8")


__all__ = [
    "PREVIEW_ENV",
    "PREVIEW_START_DATE",
    "RECIPE_DEFAULTS",
    "airflow_loader_template",
    "binding_set_payload",
    "connection_registry_payload",
    "credential_runtime_payload",
    "dag_spec_payload",
    "domain_payload",
    "known_legacy_airflow_loader_fingerprint",
    "pipeline_payload",
    "test_payload",
]
