"""Connector SDK file templates."""

from __future__ import annotations

from dpone.readiness.managed_utils import _pascal


def _connector_template(name: str) -> str:
    class_name = _pascal(name)
    return f'''from __future__ import annotations\n\n\nclass {class_name}Connector:\n    """Connector skeleton generated by dpone connector SDK."""\n\n    def __init__(self, **config):\n        self.config = dict(config)\n\n    def redacted_config(self) -> dict[str, object]:\n        return {{key: ("***" if "password" in key.lower() else value) for key, value in self.config.items()}}\n'''


def _source_template(name: str) -> str:
    return f'''from __future__ import annotations\n\n\nclass {_pascal(name)}Source:\n    """Source skeleton; implement extract(load_config, state)."""\n\n    def __init__(self, connector):\n        self.connector = connector\n'''


def _sink_template(name: str) -> str:
    return f'''from __future__ import annotations\n\n\nclass {_pascal(name)}Sink:\n    """Sink skeleton; implement load(load_config, payload)."""\n\n    def __init__(self, connector):\n        self.connector = connector\n'''


def _connector_test_template(name: str) -> str:
    return f"""from __future__ import annotations\n\nfrom dpone_ext.{name}.connector import {_pascal(name)}Connector\n\n\ndef test_{name}_connector_redacts_passwords() -> None:\n    connector = {_pascal(name)}Connector(password="secret", host="example.com")\n\n    assert connector.redacted_config()["password"] == "***"\n    assert connector.redacted_config()["host"] == "example.com"\n"""


def _connector_doc_template(name: str) -> str:
    return f"# {name} connector\n\nGenerated by `dpone connectors scaffold {name}`. Fill in auth, source/sink capabilities, examples, and certification evidence.\n"


__all__ = [
    "_connector_doc_template",
    "_connector_template",
    "_connector_test_template",
    "_sink_template",
    "_source_template",
]
