"""Receipt and rollback helpers for one workload-init apply operation."""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from dpone.manifest.loader import ManifestLoaderRouter
    from dpone.readiness.airflow_pipeline_source import ConfinedFileCreation, ConfinedFileRollbackOutcome
    from dpone.readiness.workload_init_catalog_storage import CatalogPatchReceipt


from collections.abc import Callable
from dataclasses import dataclass, replace
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any

from dpone.readiness.airflow_scaffold_apply import ScaffoldApplyPlan, ScaffoldFile, ScaffoldFileSystem
from dpone.readiness.airflow_self_service_models import Change
from dpone.security_redaction import redact_text


@dataclass(frozen=True)
class RollbackReport:
    """Outcome of reversing receipts owned by one workload-init attempt."""

    issues: tuple[str, ...]
    recovery_artifacts: tuple[str, ...]

    @property
    def status(self) -> str:
        return "recovery_required" if self.issues or self.recovery_artifacts else "rolled_back"


class ReceiptScaffoldFileSystem(ScaffoldFileSystem):
    """Capture exact scaffold creations so workload init can roll them back."""

    def __init__(self, root: str | Path) -> None:
        super().__init__(root)
        self.created: list[ConfinedFileCreation] = []

    def create(self, file: ScaffoldFile) -> ConfinedFileCreation | None:
        receipt = super().create(file)
        if receipt is not None:
            self.created.append(receipt)
        return receipt

    def rollback(self, created: ConfinedFileCreation) -> ConfinedFileRollbackOutcome:
        outcome = super().rollback(created)
        self.created.remove(created)
        return outcome


def rollback_workload_init(
    *,
    catalog_receipts: list[CatalogPatchReceipt] | tuple[CatalogPatchReceipt, ...],
    scaffold_filesystem: ReceiptScaffoldFileSystem,
    repo_root: Path,
    catalog_rollback: Callable[..., None],
    initial_error: OSError | None = None,
    known_issues: tuple[str, ...] = (),
    known_recovery_artifacts: tuple[str, ...] = (),
) -> RollbackReport:
    """Reverse catalog then scaffold receipts and retain every recovery signal."""

    issues = [*known_issues, *_error_rollback_issues(initial_error)]
    recovery_artifacts = [*known_recovery_artifacts, *_error_recovery_artifacts(initial_error)]
    for catalog_receipt in reversed(catalog_receipts):
        try:
            catalog_rollback(catalog_receipt, repo_root=repo_root)
        except Exception as exc:  # noqa: BLE001 - every compensation must be attempted
            issues.append(f"{catalog_receipt.path.as_posix()}: {redact_text(str(exc)) or 'rollback failed'}")
            recovery_artifacts.extend(_error_recovery_artifacts(exc))
    for scaffold_receipt in reversed(tuple(scaffold_filesystem.created)):
        try:
            outcome = scaffold_filesystem.rollback(scaffold_receipt)
        except Exception as exc:  # noqa: BLE001 - every compensation must be attempted
            issues.append(f"{scaffold_receipt.path.as_posix()}: {redact_text(str(exc)) or 'rollback failed'}")
            recovery_artifacts.extend(_error_recovery_artifacts(exc))
        else:
            if outcome.recovery_path is not None:
                recovery_artifacts.append(outcome.recovery_path.as_posix())
    return RollbackReport(
        issues=tuple(dict.fromkeys(issues)),
        recovery_artifacts=tuple(dict.fromkeys(recovery_artifacts)),
    )


def preflight_workload_set(
    filesystem: ScaffoldFileSystem,
    path: Path,
) -> tuple[ScaffoldFile | None, Change | None]:
    """Plan a missing workload set through the same no-follow scaffold boundary."""

    try:
        existing = filesystem.read(path)
    except OSError as exc:
        return None, Change(
            "conflict",
            path.as_posix(),
            str(exc) or "Workload-set path cannot be accessed safely.",
        )
    if existing is not None:
        return None, None
    return (
        ScaffoldFile.yaml(
            path,
            {"gitops": {"includes": [{"path": "domains/*.yaml"}]}},
        ),
        None,
    )


def recovery_artifacts_from_changes(changes: tuple[Change, ...]) -> tuple[str, ...]:
    """Collect project-relative recovery paths from an apply receipt."""

    return tuple(dict.fromkeys(change.path for change in changes if change.action == "recovery"))


def validate_generated_manifest(
    loader: ManifestLoaderRouter,
    scaffold_files: tuple[ScaffoldFile, ...],
    *,
    manifest_rel: str,
) -> dict[str, Any]:
    """Validate generated bytes in an isolated tree before repository mutation."""

    try:
        with TemporaryDirectory(prefix="dpone-workload-init-") as temporary:
            temporary_root = Path(temporary)
            for file in scaffold_files:
                target = temporary_root / file.path
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(file.text, encoding="utf-8")
            return _validate_manifest(
                loader,
                temporary_root / manifest_rel,
                reported_path=manifest_rel,
            )
    except OSError as exc:
        return {"passed": False, "message": str(exc)}


def scaffold_apply_failure_receipt(
    error: OSError,
    fallback: ScaffoldApplyPlan,
    *,
    rollback_issues: tuple[str, ...] = (),
    recovery_artifacts: tuple[str, ...] = (),
) -> ScaffoldApplyPlan:
    """Adapt the scaffold adapter's exact failure receipt for workload init."""

    receipt = getattr(error, "scaffold_receipt", None)
    source = receipt if isinstance(receipt, ScaffoldApplyPlan) else fallback
    failed = list(source.changes)
    if not failed:
        return source
    index = next(
        (index for index, change in enumerate(failed) if change.action in {"failed", "conflict", "create"}),
        0,
    )
    message = failed[index].message or str(error) or "Scaffold apply failed safely."
    issues = tuple(dict.fromkeys((*source.rollback_issues, *rollback_issues)))
    if issues:
        message = f"{message} Workload init rollback requires recovery: {'; '.join(issues)}"
    failed[index] = replace(
        failed[index],
        action="conflict",
        message=message,
    )
    return ScaffoldApplyPlan(
        changes=tuple(failed),
        rollback_journal=source.rollback_journal,
        rollback_issues=issues,
        recovery_artifacts=tuple(dict.fromkeys((*source.recovery_artifacts, *recovery_artifacts))),
        apply_failed=True,
    )


def unit_of_work_details(
    status: str,
    *,
    recovery_artifacts: tuple[str, ...] = (),
    issues: tuple[str, ...] = (),
) -> dict[str, Any]:
    """Render the additive workload-init receipt summary."""

    details: dict[str, Any] = {
        "status": status,
        "recovery_artifacts": list(recovery_artifacts),
    }
    if issues:
        details["issues"] = list(issues)
    return details


def _validate_manifest(
    loader: ManifestLoaderRouter,
    manifest_path: Path,
    *,
    reported_path: str,
) -> dict[str, Any]:
    try:
        loader.load(manifest_path, metadata_only=True)
    except Exception as exc:  # noqa: BLE001 - surface validation message to CLI
        return {"passed": False, "message": str(exc)}
    return {"passed": True, "manifest": reported_path}


def _error_recovery_artifacts(error: Exception | None) -> tuple[str, ...]:
    if error is None:
        return ()
    raw_artifacts = getattr(error, "recovery_artifacts", ())
    if isinstance(raw_artifacts, str | Path):
        raw_artifacts = (raw_artifacts,)
    artifacts = [str(path) for path in raw_artifacts]
    receipt = getattr(error, "scaffold_receipt", None)
    if isinstance(receipt, ScaffoldApplyPlan):
        artifacts.extend(receipt.recovery_artifacts)
        artifacts.extend(change.path for change in receipt.changes if change.action == "recovery")
    return tuple(dict.fromkeys(artifacts))


def _error_rollback_issues(error: Exception | None) -> tuple[str, ...]:
    if error is None:
        return ()
    receipt = getattr(error, "scaffold_receipt", None)
    if not isinstance(receipt, ScaffoldApplyPlan):
        return ()
    return receipt.rollback_issues


__all__ = [
    "ReceiptScaffoldFileSystem",
    "RollbackReport",
    "preflight_workload_set",
    "recovery_artifacts_from_changes",
    "rollback_workload_init",
    "scaffold_apply_failure_receipt",
    "unit_of_work_details",
    "validate_generated_manifest",
]
