"""Capabilities required to settle a retained restricted-writer verification."""

from typing import Protocol


class VerifySettlementOrigin(Protocol):
    def assert_verify_settlement(self, retained: object, *, deadline: float) -> None: ...
    def record_verify_local_containment(self, proof: object, *, deadline: float) -> object: ...
    def record_verify_remote_settlement(self, proof: object, *, deadline: float) -> object: ...


class SettlementEvidence(Protocol):
    @property
    def observation(self): ...
    def write(self, record: object, *, deadline: float): ...
    def close(self, *, deadline: float) -> None: ...


class VerifyCoordinator(Protocol):
    @property
    def observation(self): ...
    def execute(self, request: object, *, deadline: float): ...
    def close(self, *, deadline: float) -> None: ...


class SettlementOperations(Protocol):
    completion_type: type
    snapshot_type: type
    process_type: type
    directory_type: type
    record_type: type

    def validate_result(self, result: object, request: object) -> None: ...
    def authority_digest(self, result: object) -> str: ...
    def operation_digest(self, identity: object) -> str: ...
    def attempt_digest(self, attempt: object) -> str: ...
    def settlement_record(self, attempt: str, operation: str, completion: object) -> object: ...
    def validate_record(self, value: object) -> None: ...
    def expected_advance(self, state: object, event: object) -> object: ...
    def local_event(self, operation: str, process: object, authentication: str, evidence: str) -> object: ...
    def remote_event(self, operation: str, session: object, authority: str, evidence: str) -> object: ...
    def local_proof(self, attempt: str, operation_id: object, process: object, evidence: str) -> object: ...
    def remote_proof(self, attempt: str, operation_id: object, authority: str, evidence: str) -> object: ...
