"""Finite lossless catalog projections; no connection or arbitrary SQL port."""

from typing import Any, Protocol

from dpone.contracts.mssql_tds_api import (
    TdsAttemptOwnership,
    TdsCoordinatorAuthority,
    TdsCoordinatorIdentity,
    TdsProcessIdentity,
)


class SqlClientGrantCatalogPort(Protocol):
    identity: TdsCoordinatorIdentity
    execution_owner: TdsAttemptOwnership
    process: TdsProcessIdentity
    authority: TdsCoordinatorAuthority

    def guard(self) -> TdsCoordinatorAuthority: ...
    def read_own_incarnation(self) -> list[Any]:
        """Read the fixed own-session projection without accepting SQL text."""
        ...

    def own_incarnation(self, statement: str) -> list[Any]: ...
    def writer_admission(self, database_id: int, login: str) -> list[Any]: ...
    def principals(self, name: str, sid: bytes) -> list[Any]: ...
    def permissions(self, writer_id: int, public_id: int, *, limit: int) -> list[Any]: ...
    def member(self, object_id: int) -> list[Any]: ...
    def members(self, object_ids: tuple[int, ...]) -> list[Any]: ...
    def object_properties(self, schema_id: int, table: str) -> list[Any]: ...
    def object_properties_batch(self, object_ids: tuple[int, ...]) -> list[Any]: ...
    def features(self, object_id: int) -> list[Any]: ...
    def features_batch(self, object_ids: tuple[int, ...]) -> list[Any]: ...
    def columns(self, object_id: int) -> list[Any]: ...
    def columns_batch(self, object_ids: tuple[int, ...]) -> list[Any]: ...
