"""Produce native project documents through the existing verified archive ports."""

from __future__ import annotations

from hashlib import sha256
from pathlib import Path
from tempfile import TemporaryDirectory
from typing import Any

from dpone.adapters.native_project_documents import NativeProjectDocumentReader
from dpone.contracts.dbt_project_bundle import DbtProjectBundle, DbtProjectBundleArtifact
from dpone.contracts.dbt_publish_models import DbtPublishIntent
from dpone.contracts.dbt_publish_schema_contract_v4 import require_native_document_selection, validate_native_policy_v4
from dpone.contracts.native_delivery import NativePolicyDocumentRef
from dpone.contracts.native_project_documents import (
    NATIVE_INTENT_MEMBER,
    NATIVE_POLICY_MEMBER,
    decode_native_project_intent,
    encode_native_project_intent,
)
from dpone.ports.dbt_project_bundle import DbtProjectBundleOperations
from dpone.ports.dbt_release_files import ConfinedReleaseFileReader


class NativeProjectDocuments:
    """Capture one native intent and full selected policy without editing sources.

    The project must explicitly admit the ``dpone`` asset path. Generated files
    are added only to an owned extracted snapshot. No project configuration,
    source code, package environment or legacy archive behavior is rewritten.
    This producer performs no runtime qualification, credentials or dbt dispatch.
    """

    def __init__(
        self,
        *,
        bundles: DbtProjectBundleOperations,
        read_file: ConfinedReleaseFileReader,
        max_policy_bytes: int,
    ) -> None:
        if type(max_policy_bytes) is not int or max_policy_bytes <= 0:
            raise ValueError("native documents require an explicit positive metadata bound")
        self._bundles = bundles
        self._read = read_file
        self._documents = NativeProjectDocumentReader(read_file=read_file, max_policy_bytes=max_policy_bytes)
        self._maximum = max_policy_bytes

    def build(
        self,
        project_root: Path,
        *,
        policy: bytes,
        intent: DbtPublishIntent,
        model_storage: str = "rowstore_none",
    ) -> DbtProjectBundleArtifact:
        """Return an immutable archive containing exact canonical generated members."""
        validated = validate_native_policy_v4(policy, max_bytes=self._maximum)
        if type(intent) is not DbtPublishIntent:
            raise ValueError("native document production requires an exact normalized intent")
        require_native_document_selection(
            validated,
            profile=intent.profile,
            workflow=intent.workflow,
            layout=model_storage,
            strategy_mode=intent.strategy_mode,
        )
        descriptor = NativePolicyDocumentRef(NATIVE_POLICY_MEMBER, "sha256:" + sha256(policy).hexdigest(), len(policy))
        intent_bytes = encode_native_project_intent(intent, descriptor, model_storage=model_storage)
        if len(intent_bytes) > self._maximum:
            raise ValueError("generated native intent exceeds the metadata bound")
        original = self._bundles.build(project_root)
        with TemporaryDirectory(prefix="dpone-native-documents-") as temporary:
            snapshot = Path(temporary) / "project"
            self._bundles.extract(original.archive, snapshot)
            self._bundles.verify(original.archive, snapshot)
            for relative, payload in ((NATIVE_POLICY_MEMBER, policy), (NATIVE_INTENT_MEMBER, intent_bytes)):
                path = snapshot / relative
                path.parent.mkdir(parents=True, exist_ok=True)
                if path.exists() or path.is_symlink():
                    if self._read(snapshot, relative, max_bytes=self._maximum) != payload:
                        raise ValueError("existing native project member differs from selected generated bytes")
                else:
                    with path.open("xb") as output:
                        output.write(payload)
            produced = self._bundles.build(snapshot)
            # Re-extract the actual returned archive; checking files before its
            # producer runs would not prove generated members were admitted.
            roundtrip = Path(temporary) / "roundtrip"
            bundle = self._bundles.extract(produced.archive, roundtrip)
            self._bundles.verify(produced.archive, roundtrip)
            observed_policy, observed_intent = self.read(roundtrip, bundle)
            if observed_policy != policy or observed_intent != decode_native_project_intent(
                intent_bytes,
                max_bytes=self._maximum,
            ):
                raise ValueError("captured native documents differ from generated originals")
            return produced

    def read(self, project_root: Path, bundle: DbtProjectBundle) -> tuple[bytes, dict[str, Any]]:
        """Authenticate the generated members of an already verified archive."""
        return self._documents.read(project_root, bundle)
