version: 1
entries:
- src_system: example_app
  src_database: demo_source
  host: 192.0.2.36
  type: postgres
- src_system: incidents
  src_database: incidents
  host: 198.51.100.23
  type: postgres
- src_system: example_search
  src_database: example_search_metrics
  host: 203.0.113.73
  type: postgres
- src_system: example_events
  src_database: example_events
  host: clickhouse.example.invalid
  type: clickhouse
- src_system: appsflyer
  src_database: api
  host: hq1_appsflyer_com
  type: api
- src_system: mindbox
  src_database: api
  host: api_mindbox_ru
  type: api
- src_system: cbr
  src_database: api
  host: cbr_ru
  type: api
- src_system: fasttrack
  src_database: api
  host: dashboard_fstrk_io
  type: api
- src_system: similarweb
  src_database: api
  host: api_similarweb_com
  type: api
- src_system: openexchangerates
  src_database: api
  host: openexchangerates_org
  type: api
- src_system: google_ads
  src_database: api
  host: googleads_googleapis_com
  type: api
- src_system: google_sheets
  src_database: api
  host: sheets_googleapis_com
  type: api
- src_system: yandex_webmaster
  src_database: api
  host: api_webmaster_yandex_net
  type: api
