from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS_BY_MODULE: dict[str, tuple[str, ...]] = {
    "dpone.services.ops": (
        "cmd_approval_record",
        "cmd_artifact_index",
        "cmd_benchmark_baseline",
        "cmd_benchmark_slo_gate",
        "cmd_catalog_publish",
        "cmd_cdc_apply_certification",
        "cmd_cdc_compare_repair",
        "cmd_cdc_handoff",
        "cmd_cdc_materialize_clickhouse",
        "cmd_cdc_materialize_clickhouse_typed",
        "cmd_cdc_observability_evidence",
        "cmd_cdc_promotion_gate",
        "cmd_cdc_quarantine_inspect",
        "cmd_cdc_recovery_evidence",
        "cmd_cdc_repair_execute",
        "cmd_cdc_replay_execute",
        "cmd_cdc_resync_execute",
        "cmd_cdc_resync_plan",
        "cmd_cdc_retention_check",
        "cmd_cdc_runtime_run",
        "cmd_cdc_schema_apply",
        "cmd_cdc_schema_evolution_evidence",
        "cmd_certification_history",
        "cmd_certification_pack",
        "cmd_certification_run",
        "cmd_change_request",
        "cmd_connection_doctor",
        "cmd_connector_badges",
        "cmd_contract_check",
        "cmd_dbt_lineage",
        "cmd_deploy_render",
        "cmd_deployment_record",
        "cmd_diff",
        "cmd_docs_publish_pack",
        "cmd_env_drift",
        "cmd_evidence_bundle",
        "cmd_evidence_chain",
        "cmd_go_live_gate",
        "cmd_incident_pack",
        "cmd_industrial_readiness",
        "cmd_lineage_export",
        "cmd_live_certification_plan",
        "cmd_live_state_reconciliation",
        "cmd_managed_credentials_readiness",
        "cmd_manifest_bundle",
        "cmd_marketplace",
        "cmd_observability_pack",
        "cmd_package_commit",
        "cmd_package_start",
        "cmd_performance_certification",
        "cmd_policy_evaluate",
        "cmd_post_deploy_verify",
        "cmd_pre_release_checklist",
        "cmd_production_maturity",
        "cmd_quarantine_export",
        "cmd_quarantine_replay",
        "cmd_reconcile",
        "cmd_recovery_plan",
        "cmd_release_close",
        "cmd_release_evidence_pack",
        "cmd_release_gate",
        "cmd_release_orchestrator",
        "cmd_release_promote",
        "cmd_release_rc_collect",
        "cmd_release_rc_finalize",
        "cmd_rollback_apply",
        "cmd_rollback_execute",
        "cmd_rollback_plan",
        "cmd_route_bootstrap",
        "cmd_route_attestation_build",
        "cmd_route_attestation_verify",
        "cmd_route_certification_pack",
        "cmd_route_certify",
        "cmd_route_certify_release",
        "cmd_route_conformance",
        "cmd_route_data_quality",
        "cmd_route_doctor",
        "cmd_route_execution_ledger",
        "cmd_route_live_certification",
        "cmd_route_rc_execute",
        "cmd_route_rc_orchestrator",
        "cmd_route_readiness",
        "cmd_route_reconciliation_repair",
        "cmd_route_refresh_capture_snapshots",
        "cmd_route_refresh_execute",
        "cmd_route_refresh_plan",
        "cmd_route_refresh_verify",
        "cmd_route_release_finalize",
        "cmd_route_release_gate",
        "cmd_route_run_supervisor",
        "cmd_route_schema_evolution",
        "cmd_route_state_promote",
        "cmd_route_transport_certification",
        "cmd_run_registry",
        "cmd_runbook_pack",
        "cmd_security_audit",
        "cmd_slo_evaluate",
        "cmd_source_discover",
        "cmd_staging_evidence",
    ),
    "dpone.commands.ops_parsers_artifacts": (
        "register_benchmark_baseline_parser",
        "register_benchmark_slo_gate_parser",
        "register_catalog_publish_parser",
        "register_cdc_apply_certification_parser",
        "register_cdc_handoff_parser",
        "register_cdc_materialize_clickhouse_parser",
        "register_cdc_materialize_clickhouse_typed_parser",
        "register_cdc_observability_evidence_parser",
        "register_cdc_promotion_gate_parser",
        "register_cdc_recovery_evidence_parser",
        "register_cdc_runtime_run_parser",
        "register_cdc_schema_evolution_evidence_parser",
        "register_certification_pack_parser",
        "register_dbt_lineage_parser",
        "register_deploy_render_parser",
        "register_docs_publish_pack_parser",
        "register_lineage_export_parser",
        "register_live_certification_plan_parser",
        "register_live_state_reconciliation_parser",
        "register_managed_credentials_readiness_parser",
        "register_manifest_bundle_parser",
        "register_observability_pack_parser",
        "register_performance_certification_parser",
        "register_pre_release_checklist_parser",
        "register_reconcile_parser",
        "register_recovery_plan_parser",
        "register_release_evidence_pack_parser",
        "register_route_certification_pack_parser",
        "register_run_registry_parser",
        "register_runbook_pack_parser",
        "register_staging_evidence_parser",
    ),
    "dpone.commands.ops_parsers_cdc_compare_repair": (
        "register_cdc_compare_repair_parser",
        "register_cdc_repair_execute_parser",
    ),
    "dpone.commands.ops_parsers_cdc_replay": (
        "register_cdc_quarantine_inspect_parser",
        "register_cdc_replay_execute_parser",
    ),
    "dpone.commands.ops_parsers_cdc_retention_resync": (
        "register_cdc_resync_execute_parser",
        "register_cdc_resync_plan_parser",
        "register_cdc_retention_check_parser",
    ),
    "dpone.commands.ops_parsers_cdc_schema_apply": ("register_cdc_schema_apply_parser",),
    "dpone.commands.ops_parsers_safe_sample": ("register_safe_sample_runtime_run_parser",),
    "dpone.commands.ops_safe_sample_runtime_cmd": ("cmd_safe_sample_runtime_run",),
    "dpone.commands.ops_parsers_core": (
        "register_approval_record_parser",
        "register_artifact_index_parser",
        "register_certification_history_parser",
        "register_certification_run_parser",
        "register_change_request_parser",
        "register_connector_badges_parser",
        "register_contract_check_parser",
        "register_deployment_record_parser",
        "register_diff_parser",
        "register_env_drift_parser",
        "register_evidence_bundle_parser",
        "register_evidence_chain_parser",
        "register_go_live_gate_parser",
        "register_incident_pack_parser",
        "register_industrial_readiness_parser",
        "register_marketplace_parser",
        "register_package_commit_parser",
        "register_package_start_parser",
        "register_policy_evaluate_parser",
        "register_post_deploy_verify_parser",
        "register_production_maturity_parser",
        "register_quarantine_export_parser",
        "register_quarantine_replay_parser",
        "register_release_close_parser",
        "register_release_gate_parser",
        "register_release_orchestrator_parser",
        "register_release_promote_parser",
        "register_release_rc_collect_parser",
        "register_release_rc_finalize_parser",
        "register_rollback_apply_parser",
        "register_rollback_execute_parser",
        "register_rollback_plan_parser",
        "register_security_audit_parser",
        "register_slo_evaluate_parser",
    ),
    "dpone.commands.ops_parsers_route_certify_release": ("register_route_certify_release_parser",),
    "dpone.commands.ops_parsers_route_attestation": (
        "register_route_attestation_build_parser",
        "register_route_attestation_verify_parser",
    ),
    "dpone.commands.ops_parsers_route_conformance": ("register_route_conformance_parser",),
    "dpone.commands.ops_parsers_route_onboarding": (
        "register_connection_doctor_parser",
        "register_route_bootstrap_parser",
        "register_route_doctor_parser",
        "register_source_discover_parser",
    ),
    "dpone.commands.ops_parsers_route_release_finalize": ("register_route_release_finalize_parser",),
    "dpone.commands.ops_parsers_route_transport": ("register_route_transport_certification_parser",),
    "dpone.commands.ops_parsers_routes": (
        "register_route_certify_parser",
        "register_route_data_quality_parser",
        "register_route_execution_ledger_parser",
        "register_route_live_certification_parser",
        "register_route_rc_execute_parser",
        "register_route_rc_orchestrator_parser",
        "register_route_readiness_parser",
        "register_route_reconciliation_repair_parser",
        "register_route_refresh_capture_snapshots_parser",
        "register_route_refresh_execute_parser",
        "register_route_refresh_plan_parser",
        "register_route_refresh_verify_parser",
        "register_route_release_gate_parser",
        "register_route_run_supervisor_parser",
        "register_route_schema_evolution_parser",
        "register_route_state_promote_parser",
    ),
}

_MODULE_BY_EXPORT = {
    export_name: module_name for module_name, export_names in _EXPORTS_BY_MODULE.items() for export_name in export_names
}

__all__ = tuple(sorted(_MODULE_BY_EXPORT))


def __getattr__(name: str) -> Any:
    module_name = _MODULE_BY_EXPORT.get(name)
    if module_name is None:
        raise AttributeError(f"{__name__!s} has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value
