from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path

from .generated_block import is_generated_doc_in_sync, sync_generated_doc

CLI_REF_START = "<!-- DPONE_CLI_REFERENCE_START -->"
CLI_REF_END = "<!-- DPONE_CLI_REFERENCE_END -->"


@dataclass(frozen=True)
class CliItem:
    name: str
    prog: str
    usage: str
    positionals: tuple[tuple[str, str], ...]
    options: tuple[tuple[str, str], ...]
    io_contract: tuple[str, ...]


@dataclass(frozen=True)
class CliSection:
    name: str
    prog: str
    items: tuple[CliItem, ...]


def build_cli_sections(parser: argparse.ArgumentParser) -> tuple[CliSection, ...]:
    sections: list[CliSection] = []
    top_sub = _find_subparsers_action(parser)
    if not top_sub:
        return tuple(sections)
    for section_name, section_parser in top_sub.choices.items():
        items = list(_build_cli_items(section_name, section_parser))
        sections.append(CliSection(name=section_name, prog=section_parser.prog, items=tuple(items)))
    return tuple(sections)


def render_cli_reference_block(parser: argparse.ArgumentParser) -> str:
    sections = build_cli_sections(parser)
    lines = [
        CLI_REF_START,
        "_This section is auto-generated by `dpone docs update-cli-reference`._",
        "",
    ]
    for section in sections:
        lines.append(f"## `{section.prog}`")
        lines.append("")
        for item in section.items:
            lines.append(f"### `{item.prog}`")
            lines.append("")
            lines.append(f"- Usage: `{item.usage}`")
            if item.positionals:
                lines.append("- Positional arguments:")
                for name, help_text in item.positionals:
                    if help_text:
                        lines.append(f"  - `{name}` — {help_text}")
                    else:
                        lines.append(f"  - `{name}`")
            if item.options:
                lines.append("- Options:")
                for name, help_text in item.options:
                    if help_text:
                        lines.append(f"  - `{name}` — {help_text}")
                    else:
                        lines.append(f"  - `{name}`")
            if item.io_contract:
                lines.append("- Output and exit contract:")
                lines.extend(f"  - {entry}" for entry in item.io_contract)
            lines.append("")
    lines.append(CLI_REF_END)
    return "\n".join(lines).rstrip() + "\n"


def sync_cli_reference_doc(doc_path: Path, *, parser: argparse.ArgumentParser) -> tuple[bool, str]:
    rendered = render_cli_reference_block(parser)
    return sync_generated_doc(
        doc_path,
        rendered_block=rendered,
        start_marker=CLI_REF_START,
        end_marker=CLI_REF_END,
    )


def is_cli_reference_doc_in_sync(doc_path: Path, *, parser: argparse.ArgumentParser) -> bool:
    rendered = render_cli_reference_block(parser)
    return is_generated_doc_in_sync(
        doc_path,
        rendered_block=rendered,
        start_marker=CLI_REF_START,
        end_marker=CLI_REF_END,
    )


def _find_subparsers_action(parser: argparse.ArgumentParser) -> argparse._SubParsersAction | None:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


def _build_cli_items(name: str, parser: argparse.ArgumentParser) -> tuple[CliItem, ...]:
    nested = _find_subparsers_action(parser)
    if not nested:
        return (_build_cli_item(name, parser),)
    items: list[CliItem] = []
    if parser.get_default("_command") is not None:
        items.append(_build_cli_item(name, parser))
    for item_name, item_parser in nested.choices.items():
        items.extend(_build_cli_items(item_name, item_parser))
    return tuple(items)


def _build_cli_item(name: str, parser: argparse.ArgumentParser) -> CliItem:
    positionals: list[tuple[str, str]] = []
    options: list[tuple[str, str]] = []
    for action in parser._actions:
        if isinstance(action, argparse._HelpAction):
            continue
        if isinstance(action, argparse._SubParsersAction):
            continue
        if action.help == argparse.SUPPRESS:
            continue
        help_text = _clean_help(action.help)
        if action.option_strings:
            options.append((_render_option_signature(action), help_text))
        else:
            positionals.append((_render_positional_signature(action), help_text))
    usage = _normalize_usage(parser.format_usage())
    return CliItem(
        name=name,
        prog=parser.prog,
        usage=usage,
        positionals=tuple(positionals),
        options=tuple(options),
        io_contract=_parser_io_contract(parser),
    )


def _normalize_usage(raw: str) -> str:
    usage = " ".join(raw.strip().split())
    if usage.startswith("usage: "):
        usage = usage[len("usage: ") :]
    usage = usage.replace(" [-h]", "")
    return " ".join(usage.split())


def _render_option_signature(action: argparse.Action) -> str:
    parts = list(action.option_strings)
    if getattr(action, "nargs", None) == 0:
        return ", ".join(parts)
    metavar = _action_metavar(action)
    if parts:
        parts[-1] = f"{parts[-1]} {metavar}"
    return ", ".join(parts)


def _render_positional_signature(action: argparse.Action) -> str:
    return _action_metavar(action).lower()


def _action_metavar(action: argparse.Action) -> str:
    mv = action.metavar or action.dest
    if isinstance(mv, tuple):
        return " ".join(str(x) for x in mv)
    return str(mv).upper()


def _clean_help(help_text: str | None) -> str:
    if not help_text or help_text == argparse.SUPPRESS:
        return ""
    return " ".join(str(help_text).strip().split())


def _parser_io_contract(parser: argparse.ArgumentParser) -> tuple[str, ...]:
    raw = getattr(parser, "_dpone_io_contract", ())
    if not isinstance(raw, tuple) or any(not isinstance(item, str) or not item for item in raw):
        return ()
    return raw
