from __future__ import annotations

from collections import Counter
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from ...metrics.python_imports import build_module_files, iter_import_occurrences
from .compatibility_registry import CompatibilityEntry
from .generated_block import is_generated_doc_in_sync, sync_generated_doc

ROADMAP_START = "<!-- DPONE_DEPRECATION_ROADMAP_START -->"
ROADMAP_END = "<!-- DPONE_DEPRECATION_ROADMAP_END -->"


@dataclass(frozen=True)
class DeprecationRoadmapRow:
    deprecated: str
    canonical: str
    scope: str
    status: str
    removal: str
    canonical_usage_count: int
    shim_usage_count: int
    top_canonical_sources: tuple[str, ...]

    @property
    def readiness(self) -> str:
        if self.canonical_usage_count == 0:
            return "ready-after-policy-window"
        return f"blocked-by-usage ({self.canonical_usage_count})"


def analyze_deprecation_roadmap(
    entries: Iterable[CompatibilityEntry],
    *,
    package_dir: Path,
    package_name: str = "dpone",
    top_sources: int = 3,
) -> tuple[DeprecationRoadmapRow, ...]:
    entries = tuple(entries)
    module_files = build_module_files(package_dir, package_name=package_name)
    occurrences = tuple(iter_import_occurrences(package_dir, package_name=package_name, module_files=module_files))
    deprecated_prefixes = tuple(entry.deprecated for entry in entries)
    rows: list[DeprecationRoadmapRow] = []
    for entry in entries:
        canonical_usage = 0
        shim_usage = 0
        by_source: Counter[str] = Counter()
        for occ in occurrences:
            if not _matches_module_prefix(occ.target_module, entry.deprecated):
                continue
            if _matches_any_prefix(occ.source_module, deprecated_prefixes):
                if not _matches_module_prefix(occ.source_module, entry.deprecated):
                    shim_usage += 1
                continue
            canonical_usage += 1
            by_source[occ.source_module] += 1
        rows.append(
            DeprecationRoadmapRow(
                deprecated=entry.deprecated,
                canonical=entry.canonical,
                scope=entry.scope,
                status=entry.status,
                removal=entry.removal,
                canonical_usage_count=canonical_usage,
                shim_usage_count=shim_usage,
                top_canonical_sources=tuple(f"{name} ({count})" for name, count in by_source.most_common(top_sources)),
            )
        )
    return tuple(sorted(rows, key=lambda x: (x.canonical_usage_count > 0, x.deprecated)))


def render_deprecation_roadmap_block(rows: Iterable[DeprecationRoadmapRow]) -> str:
    rows = tuple(rows)
    ready = sum(1 for row in rows if row.canonical_usage_count == 0)
    blocked = len(rows) - ready
    lines = [
        ROADMAP_START,
        "_This section is auto-generated by `dpone docs update-deprecation-roadmap`._",
        "",
        f"- Registry entries: **{len(rows)}**",
        f"- Ready after policy window: **{ready}**",
        f"- Blocked by remaining canonical imports: **{blocked}**",
        "",
        "| Deprecated path | Canonical path | Status | Scope | Canonical imports | Shim imports | Readiness | Removal policy |",
        "|---|---|---|---|---:|---:|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| `{row.deprecated}` | `{row.canonical}` | {row.status} | {row.scope} | {row.canonical_usage_count} | {row.shim_usage_count} | {row.readiness} | {row.removal} |"
        )
        if row.top_canonical_sources:
            lines.append(
                "|  |  |  |  |  |  | " + f"_Top canonical sources: {', '.join(row.top_canonical_sources)}_ |  |"
            )
    lines.append(ROADMAP_END)
    return "\n".join(lines)


def sync_deprecation_roadmap_doc(doc_path: Path, *, rendered_block: str) -> tuple[bool, str]:
    return sync_generated_doc(
        doc_path,
        rendered_block=rendered_block,
        start_marker=ROADMAP_START,
        end_marker=ROADMAP_END,
    )


def is_deprecation_roadmap_doc_in_sync(doc_path: Path, *, rendered_block: str) -> bool:
    return is_generated_doc_in_sync(
        doc_path,
        rendered_block=rendered_block,
        start_marker=ROADMAP_START,
        end_marker=ROADMAP_END,
    )


def _matches_module_prefix(module_name: str, prefix: str) -> bool:
    return module_name == prefix or module_name.startswith(prefix + ".")


def _matches_any_prefix(module_name: str, prefixes: Iterable[str]) -> bool:
    return any(_matches_module_prefix(module_name, prefix) for prefix in prefixes)
