from __future__ import annotations

from pathlib import Path
from typing import Any

from dpone.gitops.schema_contract_primitives import GitOpsSchemaContract
from dpone.gitops.schema_contracts import gitops_schema_contracts

from .generated_block import is_generated_doc_in_sync, sync_generated_doc

GITOPS_SCHEMA_REF_START = "<!-- DPONE_GITOPS_SCHEMA_REFERENCE_START -->"
GITOPS_SCHEMA_REF_END = "<!-- DPONE_GITOPS_SCHEMA_REFERENCE_END -->"


def render_gitops_schema_reference_block() -> str:
    contracts = tuple(sorted(gitops_schema_contracts(), key=lambda contract: contract.name))
    lines = [
        GITOPS_SCHEMA_REF_START,
        "_This section is auto-generated by `dpone docs update-gitops-schema-reference`._",
        "",
        f"Registered contracts: **{len(contracts)}**.",
        "",
        "Use the schema catalog CLI for CI, IDE integrations, and platform automation:",
        "",
        "- `dpone gitops schema list --prefix dpone.safe-sample`",
        "- `dpone gitops schema show dpone.release-set.v1`",
        "- `dpone gitops schema validate --kind dpone.safe-sample-runtime-run.v1 --payload runtime-run.json`",
        "",
        "```bash",
        "dpone gitops schema list --prefix dpone.safe-sample",
        "dpone gitops schema show dpone.release-set.v1",
        "dpone gitops schema validate --kind dpone.safe-sample-runtime-run.v1 --payload runtime-run.json",
        "```",
        "",
        "| Name | Kind | Schema | Required fields |",
        "| --- | --- | --- | --- |",
    ]
    for contract in contracts:
        lines.append(_render_contract_row(contract))
    lines.append(GITOPS_SCHEMA_REF_END)
    return "\n".join(lines).rstrip() + "\n"


def sync_gitops_schema_reference_doc(doc_path: Path) -> tuple[bool, str]:
    return sync_generated_doc(
        doc_path,
        rendered_block=render_gitops_schema_reference_block(),
        start_marker=GITOPS_SCHEMA_REF_START,
        end_marker=GITOPS_SCHEMA_REF_END,
    )


def is_gitops_schema_reference_doc_in_sync(doc_path: Path) -> bool:
    return is_generated_doc_in_sync(
        doc_path,
        rendered_block=render_gitops_schema_reference_block(),
        start_marker=GITOPS_SCHEMA_REF_START,
        end_marker=GITOPS_SCHEMA_REF_END,
    )


def _render_contract_row(contract: GitOpsSchemaContract) -> str:
    schema_id = str(contract.schema.get("$id") or "")
    required = _render_required(contract.schema)
    return f"| `{contract.name}` | `{contract.kind}` | [schema]({schema_id}) | {required} |"


def _render_required(schema: dict[str, Any]) -> str:
    required = schema.get("required")
    fields = [str(item) for item in required if str(item).strip()] if isinstance(required, list) else []
    conditional = _conditional_required(schema)
    if not fields and not conditional:
        return "-"
    rendered = ", ".join(f"`{field}`" for field in fields)
    if conditional:
        prefix = "; " if rendered else ""
        rendered += prefix + "conditional: " + ", ".join(f"`{field}`" for field in conditional)
    return rendered


def _conditional_required(schema: dict[str, Any]) -> tuple[str, ...]:
    fields: set[str] = set()
    for clause in schema.get("allOf", ()):
        if not isinstance(clause, dict):
            continue
        consequence = clause.get("then")
        if not isinstance(consequence, dict):
            continue
        required = consequence.get("required")
        if isinstance(required, list):
            fields.update(str(item) for item in required if str(item).strip())
    return tuple(sorted(fields))


__all__ = [
    "GITOPS_SCHEMA_REF_END",
    "GITOPS_SCHEMA_REF_START",
    "is_gitops_schema_reference_doc_in_sync",
    "render_gitops_schema_reference_block",
    "sync_gitops_schema_reference_doc",
]
