"""Generated reference for public manifest and authoring JSON Schemas."""

from __future__ import annotations

import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

from dpone.services.docs.errors import DocsConfigurationError

from .generated_block import is_generated_doc_in_sync, sync_generated_doc

MANIFEST_SCHEMA_REF_START = "<!-- DPONE_MANIFEST_SCHEMA_REFERENCE_START -->"
MANIFEST_SCHEMA_REF_END = "<!-- DPONE_MANIFEST_SCHEMA_REFERENCE_END -->"


def render_manifest_schema_reference_block(schema_root: Path) -> str:
    """Render every public schema directly from the canonical schema directory."""

    schemas = tuple(_load_schema(path) for path in sorted(schema_root.glob("*.schema.json")))
    if not schemas:
        raise DocsConfigurationError(f"No public manifest schemas found under {schema_root.as_posix()}")
    lines = [
        MANIFEST_SCHEMA_REF_START,
        "_This section is auto-generated by `dpone docs update-manifest-schema-reference`._",
        "",
        f"Registered schemas: **{len(schemas)}**.",
        "",
        "| Schema | Kind | Purpose | Required fields |",
        "| --- | --- | --- | --- |",
    ]
    lines.extend(_render_schema_row(path, payload) for path, payload in schemas)
    lines.append(MANIFEST_SCHEMA_REF_END)
    return "\n".join(lines).rstrip() + "\n"


def sync_manifest_schema_reference_doc(doc_path: Path, *, schema_root: Path) -> tuple[bool, str]:
    return sync_generated_doc(
        doc_path,
        rendered_block=render_manifest_schema_reference_block(schema_root),
        start_marker=MANIFEST_SCHEMA_REF_START,
        end_marker=MANIFEST_SCHEMA_REF_END,
    )


def is_manifest_schema_reference_doc_in_sync(doc_path: Path, *, schema_root: Path) -> bool:
    return is_generated_doc_in_sync(
        doc_path,
        rendered_block=render_manifest_schema_reference_block(schema_root),
        start_marker=MANIFEST_SCHEMA_REF_START,
        end_marker=MANIFEST_SCHEMA_REF_END,
    )


def _load_schema(path: Path) -> tuple[Path, dict[str, Any]]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise DocsConfigurationError(f"Public manifest schema is unreadable: {path.as_posix()}") from exc
    if not isinstance(payload, dict) or not str(payload.get("$id") or "").strip():
        raise DocsConfigurationError(f"Public manifest schema requires an object and $id: {path.as_posix()}")
    return path, payload


def _render_schema_row(path: Path, payload: Mapping[str, Any]) -> str:
    name = path.name
    url = f"https://github.com/PaulKov/dpone/blob/master/src/dpone/schema/{name}"
    purpose = _markdown_text(payload.get("description") or payload.get("title") or name)
    return f"| [{name}]({url}) | `{_schema_kind(payload)}` | {purpose} | {_required_fields(payload)} |"


def _schema_kind(payload: Mapping[str, Any]) -> str:
    properties = payload.get("properties")
    if not isinstance(properties, Mapping):
        return "-"
    for key in ("kind", "schema"):
        field = properties.get(key)
        if isinstance(field, Mapping):
            value = str(field.get("const") or "").strip()
            if value:
                return value
    return "-"


def _required_fields(payload: Mapping[str, Any]) -> str:
    required = payload.get("required")
    if not isinstance(required, list):
        return "-"
    fields = tuple(str(item).strip() for item in required if str(item).strip())
    return ", ".join(f"`{field}`" for field in fields) if fields else "-"


def _markdown_text(value: object) -> str:
    return " ".join(str(value).replace("|", "\\|").split())


__all__ = [
    "MANIFEST_SCHEMA_REF_END",
    "MANIFEST_SCHEMA_REF_START",
    "is_manifest_schema_reference_doc_in_sync",
    "render_manifest_schema_reference_block",
    "sync_manifest_schema_reference_doc",
]
