from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path

from .compatibility_registry import CompatibilityEntry
from .deprecation_roadmap import analyze_deprecation_roadmap
from .generated_block import is_generated_doc_in_sync, sync_generated_doc

PLAN_START = "<!-- DPONE_SHIM_REMOVAL_PLAN_START -->"
PLAN_END = "<!-- DPONE_SHIM_REMOVAL_PLAN_END -->"
DEFAULT_BATCH = "cleanup-release-1"


@dataclass(frozen=True)
class ShimRemovalPlanRow:
    deprecated: str
    canonical: str
    scope: str
    status: str
    removal: str
    removal_batch: str
    canonical_usage_count: int
    shim_usage_count: int
    top_canonical_sources: tuple[str, ...]

    @property
    def internal_ready(self) -> bool:
        return self.canonical_usage_count == 0

    @property
    def readiness(self) -> str:
        if self.internal_ready:
            return "ready-for-next-release"
        return f"blocked-by-canonical-imports ({self.canonical_usage_count})"

    @property
    def action(self) -> str:
        if self.scope == "package":
            return "Delete shim package and keep release-note migration section."
        return "Delete shim module and keep release-note migration section."


@dataclass(frozen=True)
class ShimRemovalReadinessReport:
    batch: str
    registry_path: str
    doc_path: str
    selected_count: int
    ready_count: int
    blocked_count: int
    doc_synced: bool
    rows: tuple[ShimRemovalPlanRow, ...]

    @property
    def ok(self) -> bool:
        return self.selected_count > 0 and self.blocked_count == 0 and self.doc_synced


def analyze_shim_removal_plan(
    entries: Iterable[CompatibilityEntry],
    *,
    package_dir: Path,
    batch: str = DEFAULT_BATCH,
    package_name: str = "dpone",
    top_sources: int = 3,
) -> tuple[ShimRemovalPlanRow, ...]:
    entries = tuple(entry for entry in entries if _matches_batch(entry, batch))
    roadmap = analyze_deprecation_roadmap(
        entries, package_dir=package_dir, package_name=package_name, top_sources=top_sources
    )
    rows = [
        ShimRemovalPlanRow(
            deprecated=row.deprecated,
            canonical=row.canonical,
            scope=row.scope,
            status=row.status,
            removal=row.removal,
            removal_batch=batch,
            canonical_usage_count=row.canonical_usage_count,
            shim_usage_count=row.shim_usage_count,
            top_canonical_sources=row.top_canonical_sources,
        )
        for row in roadmap
    ]
    return tuple(sorted(rows, key=lambda x: (not x.internal_ready, x.scope != "package", x.deprecated)))


def render_shim_removal_plan_block(rows: Iterable[ShimRemovalPlanRow], *, batch: str) -> str:
    rows = tuple(rows)
    ready_rows = tuple(row for row in rows if row.internal_ready)
    blocked_rows = tuple(row for row in rows if not row.internal_ready)
    package_rows = tuple(row for row in rows if row.scope == "package")
    module_rows = tuple(row for row in rows if row.scope == "module")

    lines = [
        PLAN_START,
        "_This section is auto-generated by `dpone docs update-shim-removal-plan`._",
        "",
        f"- Planned removal batch: **{batch}**",
        f"- Registry entries in batch: **{len(rows)}**",
        f"- Internally ready now: **{len(ready_rows)}**",
        f"- Blocked by canonical imports: **{len(blocked_rows)}**",
        f"- Package shims in batch: **{len(package_rows)}**",
        f"- Module shims in batch: **{len(module_rows)}**",
        "",
        "> This plan proves **internal readiness only**. External consumers still need a documented compatibility window and release notes before actual removal.",
        "",
        "| Deprecated path | Canonical path | Scope | Status | Canonical imports | Ready | Action |",
        "|---|---|---|---|---:|---|---|",
    ]
    for row in rows:
        lines.append(
            f"| `{row.deprecated}` | `{row.canonical}` | {row.scope} | {row.status} | {row.canonical_usage_count} | {row.readiness} | {row.action} |"
        )
        if row.top_canonical_sources:
            lines.append("|  |  |  |  |  | " + f"_Top canonical sources: {', '.join(row.top_canonical_sources)}_ |  |")

    lines.extend(
        [
            "",
            "## Suggested execution order",
            "",
            "1. Remove package shims first (broadest import surface).",
        ]
    )
    for row in package_rows:
        lines.append(f"   - `{row.deprecated}` → `{row.canonical}`")
    lines.append("2. Remove transitional module shims.")
    for row in module_rows:
        lines.append(f"   - `{row.deprecated}` → `{row.canonical}`")
    lines.extend(
        [
            "3. Run the cleanup validation checklist before merge:",
            "",
            "```bash",
            "pytest",
            "dpone docs check-docs",
            "dpone docs check-compatibility",
            "dpone docs update-cli-reference --check",
            "dpone docs update-deprecation-roadmap --check",
            f"dpone docs check-removal-readiness --batch {batch}",
            "dpone docs check-import-rules",
            "dpone docs check-layer-metrics",
            "dpone docs update-dev-metrics --check",
            "```",
            "",
            "## Release note checklist",
            "",
            "- add migration note: `from OLD import ...` → `from NEW import ...` for every removed shim;",
            "- call out the removal batch in release notes;",
            "- keep `docs/compatibility.md` and `docs/deprecation-roadmap.md` updated in the same PR.",
            PLAN_END,
        ]
    )
    return "\n".join(lines)


def sync_shim_removal_plan_doc(doc_path: Path, *, rendered_block: str) -> tuple[bool, str]:
    return sync_generated_doc(
        doc_path,
        rendered_block=rendered_block,
        start_marker=PLAN_START,
        end_marker=PLAN_END,
    )


def is_shim_removal_plan_doc_in_sync(doc_path: Path, *, rendered_block: str) -> bool:
    return is_generated_doc_in_sync(
        doc_path,
        rendered_block=rendered_block,
        start_marker=PLAN_START,
        end_marker=PLAN_END,
    )


def format_shim_removal_readiness_text(report: ShimRemovalReadinessReport) -> str:
    if report.ok:
        return (
            f"✅ Removal readiness OK for batch '{report.batch}': "
            f"{report.ready_count}/{report.selected_count} entries internally ready and docs are in sync."
        )
    lines = [
        f"Removal readiness check failed for batch '{report.batch}':",
        f"- registry: {report.registry_path}",
        f"- doc: {report.doc_path}",
        f"- selected entries: {report.selected_count}",
        f"- ready now: {report.ready_count}",
        f"- blocked: {report.blocked_count}",
        f"- doc_synced: {'yes' if report.doc_synced else 'no'}",
    ]
    if report.selected_count == 0:
        lines.append("- no entries matched the requested removal batch")
    for row in report.rows:
        if row.internal_ready:
            continue
        lines.append(f"- blocked: {row.deprecated} -> {row.canonical}")
        if row.top_canonical_sources:
            lines.append(f"    top canonical sources: {', '.join(row.top_canonical_sources)}")
    return "\n".join(lines)


def format_shim_removal_readiness_jsonable(report: ShimRemovalReadinessReport) -> dict:
    return {
        "ok": report.ok,
        "batch": report.batch,
        "registry_path": report.registry_path,
        "doc_path": report.doc_path,
        "selected_count": report.selected_count,
        "ready_count": report.ready_count,
        "blocked_count": report.blocked_count,
        "doc_synced": report.doc_synced,
        "rows": [
            {
                "deprecated": row.deprecated,
                "canonical": row.canonical,
                "scope": row.scope,
                "status": row.status,
                "removal_batch": row.removal_batch,
                "canonical_usage_count": row.canonical_usage_count,
                "shim_usage_count": row.shim_usage_count,
                "internal_ready": row.internal_ready,
                "readiness": row.readiness,
                "top_canonical_sources": list(row.top_canonical_sources),
            }
            for row in report.rows
        ],
    }


def _matches_batch(entry: CompatibilityEntry, batch: str) -> bool:
    entry_batch = (entry.removal_batch or DEFAULT_BATCH).strip()
    return entry_batch == batch
