"""Compatibility imports for canonical generic MSSQL object names."""

from __future__ import annotations

from dpone.contracts.mssql_generic_transaction_names import (
    ATTEMPT_TABLE,
    ATTEMPT_TRIGGER,
    FENCE_TABLE,
    FENCE_TRIGGER,
    GENERIC_TRANSACTION_CATALOG_VERSION,
    GENERIC_TRANSACTION_TABLES,
    GENERIC_TRANSACTION_TRIGGERS,
    OPERATION_TABLE,
    OPERATION_TRIGGER,
    RECEIPT_TABLE,
    RECEIPT_TRIGGER,
    TARGET_IDENTITY_REGISTRY_TABLE,
    TARGET_IDENTITY_REGISTRY_TRIGGER,
)

__all__ = [
    "ATTEMPT_TABLE",
    "ATTEMPT_TRIGGER",
    "FENCE_TABLE",
    "FENCE_TRIGGER",
    "GENERIC_TRANSACTION_TABLES",
    "GENERIC_TRANSACTION_TRIGGERS",
    "GENERIC_TRANSACTION_CATALOG_VERSION",
    "OPERATION_TABLE",
    "OPERATION_TRIGGER",
    "RECEIPT_TABLE",
    "RECEIPT_TRIGGER",
    "TARGET_IDENTITY_REGISTRY_TABLE",
    "TARGET_IDENTITY_REGISTRY_TRIGGER",
]
