"""Live CDC readers compatibility facade."""

from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "CDCBatch",
    "CDCChange",
    "CDCOperation",
    "CDCReader",
    "CDCEventIdentityService",
    "CDCIdempotencyReport",
    "CDCIdempotencyService",
    "MSSQLCDCReader",
    "MSSQLChangeTrackingReader",
    "MSSQLChangeTrackingReaderConfig",
    "MSSQLTableCDCReaderConfig",
    "PgOutputMessageParser",
    "PostgresLogicalCDCReader",
    "PostgresLogicalCDCReaderConfig",
    "TestDecodingMessageParser",
    "CDCCommitDecision",
    "CDCCommitGate",
    "CDCOffsetTokenComparator",
    "CDCReplayPlan",
    "CDCReplayPlanner",
    "CDCReplayStep",
    "CdcApplyReceipt",
    "CdcCompareDiff",
    "CdcCompareRepairReport",
    "CdcCompareRepairService",
    "CdcCompareRow",
    "CdcOffsetStore",
    "CdcRuntimeOrchestrator",
    "CdcRuntimePolicy",
    "CdcRuntimeRunReport",
    "CdcRuntimeStream",
    "CdcSinkApplier",
    "CdcPoisonClassifier",
    "CdcPoisonDecision",
    "CdcPoisonQuarantineReport",
    "CdcPoisonRecord",
    "CdcReplayExecutionReport",
    "CdcReplayExecutionService",
    "CdcRepairAction",
    "CdcRepairExecutionReport",
    "CdcRepairExecutionService",
    "CdcRepairPlan",
    "CdcResyncAction",
    "CdcResyncExecutionReport",
    "CdcResyncExecutionService",
    "CdcResyncPlan",
    "CdcResyncPlanReport",
    "CdcResyncPlanner",
    "CdcRetentionBounds",
    "CdcRetentionDecision",
    "CdcRetentionGapService",
    "CdcRetentionPolicy",
    "CdcRetentionReport",
    "MssqlCdcRetentionProbe",
    "MssqlChangeTrackingRetentionProbe",
    "StaticCdcRetentionProbe",
    "FileCdcPoisonQuarantine",
    "InMemoryCdcCompareReader",
    "CdcRuntimeLiveAdapterFactory",
    "ClickHouseCdcApplyPlan",
    "ClickHouseCdcLogCompareReader",
    "ClickHouseCdcMaterializationPlan",
    "ClickHouseCdcMaterializationPolicy",
    "ClickHouseCdcMaterializationReport",
    "ClickHouseCdcMaterializationService",
    "ClickHouseCdcPayloadProjector",
    "ClickHouseCdcSinkApplier",
    "ClickHouseCdcTypedParseFailure",
    "ClickHouseCdcTypedParseQuarantine",
    "ClickHouseCdcTypedColumn",
    "ClickHouseCdcTypedMaterializationPlan",
    "ClickHouseCdcTypedMaterializationPolicy",
    "ClickHouseCdcTypedMaterializationReport",
    "ClickHouseCdcTypedQualityEvidence",
    "ClickHouseCdcTypedQualityPolicy",
    "ClickHouseCdcTypedSchemaDrift",
    "ClickHouseCdcTypedMaterializationService",
    "MssqlCdcCompareReader",
    "FileCdcOffsetStore",
    "JsonCdcBatchReader",
    "LocalCdcSinkApplier",
    "SqlCdcOffsetStoreAdapter",
]

_EXPORTS: dict[str, str] = {
    "CDCBatch": "dpone.runtime.cdc.base:CDCBatch",
    "CDCChange": "dpone.runtime.cdc.base:CDCChange",
    "CDCOperation": "dpone.runtime.cdc.base:CDCOperation",
    "CDCReader": "dpone.runtime.cdc.base:CDCReader",
    "CDCEventIdentityService": "dpone.runtime.cdc.identity:CDCEventIdentityService",
    "CDCIdempotencyReport": "dpone.runtime.cdc.identity:CDCIdempotencyReport",
    "CDCIdempotencyService": "dpone.runtime.cdc.identity:CDCIdempotencyService",
    "MSSQLCDCReader": "dpone.runtime.cdc.mssql:MSSQLCDCReader",
    "MSSQLChangeTrackingReader": "dpone.runtime.cdc.mssql:MSSQLChangeTrackingReader",
    "MSSQLChangeTrackingReaderConfig": "dpone.runtime.cdc.mssql:MSSQLChangeTrackingReaderConfig",
    "MSSQLTableCDCReaderConfig": "dpone.runtime.cdc.mssql:MSSQLTableCDCReaderConfig",
    "PgOutputMessageParser": "dpone.runtime.cdc.postgres:PgOutputMessageParser",
    "PostgresLogicalCDCReader": "dpone.runtime.cdc.postgres:PostgresLogicalCDCReader",
    "PostgresLogicalCDCReaderConfig": "dpone.runtime.cdc.postgres:PostgresLogicalCDCReaderConfig",
    "TestDecodingMessageParser": "dpone.runtime.cdc.postgres:TestDecodingMessageParser",
    "CDCCommitDecision": "dpone.runtime.cdc.replay:CDCCommitDecision",
    "CDCCommitGate": "dpone.runtime.cdc.replay:CDCCommitGate",
    "CDCOffsetTokenComparator": "dpone.runtime.cdc.replay:CDCOffsetTokenComparator",
    "CDCReplayPlan": "dpone.runtime.cdc.replay:CDCReplayPlan",
    "CDCReplayPlanner": "dpone.runtime.cdc.replay:CDCReplayPlanner",
    "CDCReplayStep": "dpone.runtime.cdc.replay:CDCReplayStep",
    "CdcApplyReceipt": "dpone.runtime.cdc.runtime_models:CdcApplyReceipt",
    "CdcCompareDiff": "dpone.runtime.cdc.compare_models:CdcCompareDiff",
    "CdcCompareRepairReport": "dpone.runtime.cdc.compare_models:CdcCompareRepairReport",
    "CdcCompareRepairService": "dpone.runtime.cdc.compare:CdcCompareRepairService",
    "CdcCompareRow": "dpone.runtime.cdc.compare_models:CdcCompareRow",
    "CdcOffsetStore": "dpone.runtime.cdc.runtime_ports:CdcOffsetStore",
    "CdcRuntimeOrchestrator": "dpone.runtime.cdc.runtime_orchestrator:CdcRuntimeOrchestrator",
    "CdcRuntimePolicy": "dpone.runtime.cdc.runtime_models:CdcRuntimePolicy",
    "CdcRuntimeRunReport": "dpone.runtime.cdc.runtime_models:CdcRuntimeRunReport",
    "CdcRuntimeStream": "dpone.runtime.cdc.runtime_models:CdcRuntimeStream",
    "CdcSinkApplier": "dpone.runtime.cdc.runtime_ports:CdcSinkApplier",
    "CdcPoisonClassifier": "dpone.runtime.cdc.poison:CdcPoisonClassifier",
    "CdcPoisonDecision": "dpone.runtime.cdc.poison_models:CdcPoisonDecision",
    "CdcPoisonQuarantineReport": "dpone.runtime.cdc.poison_models:CdcPoisonQuarantineReport",
    "CdcPoisonRecord": "dpone.runtime.cdc.poison_models:CdcPoisonRecord",
    "CdcReplayExecutionReport": "dpone.runtime.cdc.replay_execution:CdcReplayExecutionReport",
    "CdcReplayExecutionService": "dpone.runtime.cdc.replay_execution:CdcReplayExecutionService",
    "CdcRepairAction": "dpone.runtime.cdc.compare_models:CdcRepairAction",
    "CdcRepairExecutionReport": "dpone.runtime.cdc.repair:CdcRepairExecutionReport",
    "CdcRepairExecutionService": "dpone.runtime.cdc.repair:CdcRepairExecutionService",
    "CdcRepairPlan": "dpone.runtime.cdc.compare_models:CdcRepairPlan",
    "CdcResyncAction": "dpone.runtime.cdc.retention_models:CdcResyncAction",
    "CdcResyncExecutionReport": "dpone.runtime.cdc.retention_models:CdcResyncExecutionReport",
    "CdcResyncExecutionService": "dpone.runtime.cdc.resync:CdcResyncExecutionService",
    "CdcResyncPlan": "dpone.runtime.cdc.retention_models:CdcResyncPlan",
    "CdcResyncPlanReport": "dpone.runtime.cdc.retention_models:CdcResyncPlanReport",
    "CdcResyncPlanner": "dpone.runtime.cdc.retention:CdcResyncPlanner",
    "CdcRetentionBounds": "dpone.runtime.cdc.retention_models:CdcRetentionBounds",
    "CdcRetentionDecision": "dpone.runtime.cdc.retention_models:CdcRetentionDecision",
    "CdcRetentionGapService": "dpone.runtime.cdc.retention:CdcRetentionGapService",
    "CdcRetentionPolicy": "dpone.runtime.cdc.retention:CdcRetentionPolicy",
    "CdcRetentionReport": "dpone.runtime.cdc.retention_models:CdcRetentionReport",
    "MssqlCdcRetentionProbe": "dpone.runtime.cdc.retention_probes:MssqlCdcRetentionProbe",
    "MssqlChangeTrackingRetentionProbe": "dpone.runtime.cdc.retention_probes:MssqlChangeTrackingRetentionProbe",
    "StaticCdcRetentionProbe": "dpone.runtime.cdc.retention_probes:StaticCdcRetentionProbe",
    "FileCdcPoisonQuarantine": "dpone.runtime.cdc.poison:FileCdcPoisonQuarantine",
    "InMemoryCdcCompareReader": "dpone.runtime.cdc.compare:InMemoryCdcCompareReader",
    "CdcRuntimeLiveAdapterFactory": "dpone.runtime.cdc.live_factory:CdcRuntimeLiveAdapterFactory",
    "ClickHouseCdcApplyPlan": "dpone.runtime.cdc.live_adapters:ClickHouseCdcApplyPlan",
    "ClickHouseCdcLogCompareReader": "dpone.runtime.cdc.compare_readers:ClickHouseCdcLogCompareReader",
    "ClickHouseCdcMaterializationPlan": "dpone.runtime.cdc.materialization:ClickHouseCdcMaterializationPlan",
    "ClickHouseCdcMaterializationPolicy": "dpone.runtime.cdc.materialization:ClickHouseCdcMaterializationPolicy",
    "ClickHouseCdcMaterializationReport": "dpone.runtime.cdc.materialization:ClickHouseCdcMaterializationReport",
    "ClickHouseCdcMaterializationService": "dpone.runtime.cdc.materialization:ClickHouseCdcMaterializationService",
    "ClickHouseCdcPayloadProjector": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcPayloadProjector",
    "ClickHouseCdcSinkApplier": "dpone.runtime.cdc.live_adapters:ClickHouseCdcSinkApplier",
    "ClickHouseCdcTypedParseFailure": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcTypedParseFailure",
    "ClickHouseCdcTypedParseQuarantine": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcTypedParseQuarantine",
    "ClickHouseCdcTypedColumn": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcTypedColumn",
    "ClickHouseCdcTypedMaterializationPlan": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcTypedMaterializationPlan",
    "ClickHouseCdcTypedMaterializationPolicy": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcTypedMaterializationPolicy",
    "ClickHouseCdcTypedMaterializationReport": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcTypedMaterializationReport",
    "ClickHouseCdcTypedQualityEvidence": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcTypedQualityEvidence",
    "ClickHouseCdcTypedQualityPolicy": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcTypedQualityPolicy",
    "ClickHouseCdcTypedSchemaDrift": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcTypedSchemaDrift",
    "ClickHouseCdcTypedMaterializationService": "dpone.runtime.cdc.typed_materialization:ClickHouseCdcTypedMaterializationService",
    "MssqlCdcCompareReader": "dpone.runtime.cdc.compare_readers:MssqlCdcCompareReader",
    "FileCdcOffsetStore": "dpone.runtime.cdc.local_runtime:FileCdcOffsetStore",
    "JsonCdcBatchReader": "dpone.runtime.cdc.local_runtime:JsonCdcBatchReader",
    "LocalCdcSinkApplier": "dpone.runtime.cdc.local_runtime:LocalCdcSinkApplier",
    "SqlCdcOffsetStoreAdapter": "dpone.runtime.cdc.live_factory:SqlCdcOffsetStoreAdapter",
}


def __getattr__(name: str) -> Any:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr = target.split(":", 1)
    value = getattr(import_module(module_name), attr)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
