"""Compatibility exports of the immutable registration contract and codec owner.

Objects preserve historical import and pickle identity; no policy is duplicated.
"""

from dpone.contracts.dbt_mssql_physical_registration import UUID as UUID
from dpone.contracts.dbt_mssql_physical_registration import DatabasePrincipal as DatabasePrincipal
from dpone.contracts.dbt_mssql_physical_registration import DatabaseRoleMapping as DatabaseRoleMapping
from dpone.contracts.dbt_mssql_physical_registration import DbtPublishingError as DbtPublishingError
from dpone.contracts.dbt_mssql_physical_registration import DedicatedObserver as DedicatedObserver
from dpone.contracts.dbt_mssql_physical_registration import MssqlDatabaseAuthorityPin as MssqlDatabaseAuthorityPin
from dpone.contracts.dbt_mssql_physical_registration import (
    MssqlPhysicalRuntimeRegistration as MssqlPhysicalRuntimeRegistration,
)
from dpone.contracts.dbt_mssql_physical_registration import NativeJsonValue as NativeJsonValue
from dpone.contracts.dbt_mssql_physical_registration import (
    NativePlatformOriginalSubject as NativePlatformOriginalSubject,
)
from dpone.contracts.dbt_mssql_physical_registration import OriginalRef as OriginalRef
from dpone.contracts.dbt_mssql_physical_registration import PhysicalRegistrationError as PhysicalRegistrationError
from dpone.contracts.dbt_mssql_physical_registration import PlatformSelection as PlatformSelection
from dpone.contracts.dbt_mssql_physical_registration import ProgramAuthority as ProgramAuthority
from dpone.contracts.dbt_mssql_physical_registration import RegisteredLimits as RegisteredLimits
from dpone.contracts.dbt_mssql_physical_registration import RegisteredPrincipals as RegisteredPrincipals
from dpone.contracts.dbt_mssql_physical_registration import SharedObserver as SharedObserver
from dpone.contracts.dbt_mssql_physical_registration import cast as cast
from dpone.contracts.dbt_mssql_physical_registration import decode_native_delivery_json as decode_native_delivery_json
from dpone.contracts.dbt_mssql_physical_registration import (
    decode_native_original_subject as decode_native_original_subject,
)
from dpone.contracts.dbt_mssql_physical_registration import (
    decode_physical_runtime_registration as decode_physical_runtime_registration,
)
from dpone.contracts.dbt_mssql_physical_registration import encode_native_delivery_json as encode_native_delivery_json
from dpone.contracts.dbt_mssql_physical_registration import (
    encode_physical_runtime_registration as encode_physical_runtime_registration,
)
from dpone.contracts.dbt_mssql_physical_registration import (
    physical_runtime_registration_digest as physical_runtime_registration_digest,
)
from dpone.contracts.dbt_mssql_physical_registration import require_physical_text as require_physical_text
from dpone.contracts.dbt_mssql_physical_registration import require_physical_uuid as require_physical_uuid
from dpone.contracts.dbt_mssql_physical_registration import require_sql_positive_integer as require_sql_positive_integer
from dpone.contracts.dbt_mssql_physical_registration import sha256 as sha256
