"""Deprecated compatibility shim for Yandex Webmaster helper imports.

Use ``dpone.runtime.sources.strategies.api.yandex_webmaster.common`` for public imports or
``dpone.runtime.sources.strategies.api.yandex_webmaster.support`` for focused helper imports.
"""

from __future__ import annotations

from dpone.runtime.sources.strategies.api.yandex_webmaster.support import (
    MOSCOW_TZ,
    YANDEX_WEBMASTER_DEFAULT_DEVICE_TYPES,
    YANDEX_WEBMASTER_DEFAULT_REGIONS,
    YANDEX_WEBMASTER_REGION_NAME_BY_ID,
    YANDEX_WEBMASTER_SCHEMA,
    YWM_SCHEMA,
    YandexWebmasterRegion,
    _coerce_float,
    _coerce_int,
    _within_window,
    aggregate_in_search_history,
    aggregate_indexing_history,
    aggregate_search_events,
    build_date_replace_predicate,
    build_query_analytics_by_region_rows,
    build_search_queries_history_rows,
    build_yandex_webmaster_host_metrics_rows,
    build_yandex_webmaster_rows,
    build_ywm_rows,
    ensure_host_metrics_daily_resource,
    merge_daily_metrics,
    parse_csv_list,
    parse_date_option,
    parse_device_types,
    parse_int_list_option,
    parse_yandex_datetime,
    resolve_regions,
    resolve_window,
    resolve_yandex_webmaster_resource,
    to_msk_date,
    validate_unique_dates,
    validate_unique_keys,
    yesterday_msk,
)

__all__ = [
    "YandexWebmasterRegion",
    "MOSCOW_TZ",
    "YANDEX_WEBMASTER_DEFAULT_DEVICE_TYPES",
    "YANDEX_WEBMASTER_DEFAULT_REGIONS",
    "YANDEX_WEBMASTER_REGION_NAME_BY_ID",
    "YANDEX_WEBMASTER_SCHEMA",
    "YWM_SCHEMA",
    "parse_date_option",
    "yesterday_msk",
    "parse_csv_list",
    "parse_device_types",
    "parse_int_list_option",
    "parse_yandex_datetime",
    "to_msk_date",
    "aggregate_indexing_history",
    "aggregate_in_search_history",
    "aggregate_search_events",
    "validate_unique_dates",
    "validate_unique_keys",
    "merge_daily_metrics",
    "ensure_host_metrics_daily_resource",
    "resolve_yandex_webmaster_resource",
    "resolve_window",
    "build_date_replace_predicate",
    "resolve_regions",
    "_within_window",
    "_coerce_float",
    "_coerce_int",
    "build_yandex_webmaster_host_metrics_rows",
    "build_search_queries_history_rows",
    "build_query_analytics_by_region_rows",
    "build_yandex_webmaster_rows",
    "build_ywm_rows",
]
