"""Canonical SQL Server projection for strategy-owned framework columns.

Snapshot-diff and SCD2 metadata is generated by dpone, not projected from a
source database.  Its SQL Server shape therefore must not depend on the
generic source-pair timestamp mapper.  This module is the single pure
authority shared by target preplanning and native staging.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

from dpone.contracts.technical_columns import TechnicalColumnCatalog, TechnicalColumnRole
from dpone.runtime.lineage.postgres_xmin_initial_metadata import (
    is_postgres_xmin_initial_metadata_route,
    target_strategy_metadata_strategy,
)
from dpone.runtime.lineage.strategy_metadata_rows import strategy_metadata_schema_columns
from dpone.runtime.sinks.mssql_preplanned_target_types import preplanned_mssql_target_type

MssqlStrategyMetadataColumnContract = tuple[str, str, bool]
MSSQL_NATIVE_STRATEGY_METADATA_CONTRACT = "dpone.mssql.native-strategy-metadata.v1"


@dataclass(frozen=True, slots=True)
class MssqlNativeStrategyMetadataColumn:
    """One target-only column generated inside typed SQL Server staging."""

    name: str
    target_type: str
    nullable: bool
    placeholder_sql: str
    generation_contract: str = MSSQL_NATIVE_STRATEGY_METADATA_CONTRACT


_TARGET_SHAPES: dict[TechnicalColumnRole, tuple[str, bool]] = {
    TechnicalColumnRole.ROW_HASH: ("varchar(64)", False),
    TechnicalColumnRole.DELETED_AT: ("datetime2(7)", True),
    TechnicalColumnRole.VALID_FROM_AT: ("datetime2(7)", False),
    TechnicalColumnRole.VALID_TO_AT: ("datetime2(7)", True),
    TechnicalColumnRole.IS_CURRENT: ("bit", False),
}


def resolve_mssql_strategy_metadata_columns(
    load_config: Any,
) -> tuple[MssqlStrategyMetadataColumnContract, ...]:
    """Return exact MSSQL types/nullability for the selected load strategy."""

    catalog = TechnicalColumnCatalog()
    by_name = {
        catalog.name(role).casefold(): (catalog.name(role), target_type, nullable)
        for role, (target_type, nullable) in _TARGET_SHAPES.items()
    }
    selected = strategy_metadata_schema_columns(target_strategy_metadata_strategy(load_config))
    result: list[MssqlStrategyMetadataColumnContract] = []
    for name, _logical_type, nullable in selected:
        canonical = by_name.get(name.casefold())
        if canonical is None:
            raise RuntimeError("mssql_strategy_metadata.column_projection_missing")
        canonical_name, target_type, target_nullable = canonical
        if name != canonical_name or nullable != target_nullable:
            raise RuntimeError("mssql_strategy_metadata.logical_catalog_drift")
        result.append(
            (
                canonical_name,
                preplanned_mssql_target_type(load_config, canonical_name, target_type),
                target_nullable,
            )
        )
    return tuple(result)


def resolve_mssql_native_strategy_metadata_columns(
    load_config: Any,
) -> tuple[MssqlNativeStrategyMetadataColumn, ...]:
    """Return XMin-initial columns generated without rewriting the COPY file."""

    if not is_postgres_xmin_initial_metadata_route(load_config):
        return ()
    output: list[MssqlNativeStrategyMetadataColumn] = []
    for name, target_type, nullable in resolve_mssql_strategy_metadata_columns(load_config):
        if name == "__dpone__row_hash":
            placeholder = f"CONVERT({target_type}, REPLICATE('0', 64))"
        elif nullable:
            placeholder = f"CONVERT({target_type}, NULL)"
        else:
            raise RuntimeError("mssql_strategy_metadata.native_placeholder_missing")
        output.append(
            MssqlNativeStrategyMetadataColumn(
                name=name,
                target_type=target_type,
                nullable=nullable,
                placeholder_sql=placeholder,
            )
        )
    return tuple(output)


def mssql_strategy_metadata_types(load_config: Any) -> dict[str, str]:
    """Return the selected immutable physical type map for native staging."""

    return {name: target_type for name, target_type, _nullable in resolve_mssql_strategy_metadata_columns(load_config)}


def mssql_strategy_metadata_nullability(load_config: Any) -> dict[str, bool]:
    """Return the selected immutable nullability map for native staging."""

    return {name: nullable for name, _target_type, nullable in resolve_mssql_strategy_metadata_columns(load_config)}


__all__ = [
    "MSSQL_NATIVE_STRATEGY_METADATA_CONTRACT",
    "MssqlNativeStrategyMetadataColumn",
    "MssqlStrategyMetadataColumnContract",
    "mssql_strategy_metadata_nullability",
    "mssql_strategy_metadata_types",
    "resolve_mssql_native_strategy_metadata_columns",
    "resolve_mssql_strategy_metadata_columns",
]
